/**
 * The curated POI catalogue for the three pilot cities.
 *
 * This replaces the previous mix of hand-written fixtures and raw OSM imports.
 * The imports were the problem: they brought in roundabouts, housing-estate
 * lawns and half a dozen unnamed "Jardin public" polygons, none of which anyone
 * would plan a day around and none of which have a photograph in existence. A
 * catalogue is a curatorial object, so it is curated — every entry is a place a
 * visitor would actually be sent to, and every entry names a Wikipedia article
 * or Commons category so the resolver can find a real picture of it.
 *
 * Fields:
 *   key             stable slug, stored as external_ref so a re-seed is idempotent
 *   city / cat      must match CITY_IDS / CATEGORY_IDS below
 *   en / fr / ar    display names
 *   dEn / dFr / dAr one-sentence blurbs, shown under the photo in the app
 *   lat / lng       fallback coordinates; Wikipedia's win when the article has them
 *   min             average visit in minutes, used by the time-budget planner
 *   radius          check-in radius in metres — wide for districts, tight for buildings
 *   hours           opening hours as free text, where the place has any
 *   wiki            article hints in preference order, "lang:Title"
 *   commonsCategory the subject's own Commons category, the best fallback
 *   commonsSearch   last-resort free-text queries
 *   commonsFile     an exact Commons file, pinned when the cascade picked wrong;
 *                   overrides every other hint, and pins the coordinates too
 */

export const CITY_IDS = {
  Algiers: '00000000-0000-4000-a000-000000000010',
  Oran: '00000000-0000-4000-a000-000000000020',
  Constantine: '00000000-0000-4000-a000-000000000030',
};

export const CATEGORY_IDS = {
  historical_monument: '00000000-0000-4000-b000-000000000001',
  museum: '00000000-0000-4000-b000-000000000002',
  park_garden: '00000000-0000-4000-b000-000000000003',
  religious_site: '00000000-0000-4000-b000-000000000004',
  viewpoint: '00000000-0000-4000-b000-000000000005',
  cultural_venue: '00000000-0000-4000-b000-000000000006',
  beach: '00000000-0000-4000-b000-000000000007',
};

export const CATALOGUE = [
  // ===========================================================================
  // ALGIERS
  // ===========================================================================
  {
    key: 'dz-alg-casbah',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7853, lng: 3.0596, min: 120, radius: 300,
    en: 'Casbah of Algiers', fr: "Casbah d'Alger", ar: 'قصبة الجزائر',
    dEn: 'A UNESCO-listed Ottoman citadel of stepped alleys, tiled courtyards and terraces falling towards the bay.',
    dFr: "Citadelle ottomane classée à l'UNESCO : ruelles en escalier, patios carrelés et terrasses dévalant vers la baie.",
    dAr: 'قلعة عثمانية مصنفة ضمن التراث العالمي، بأزقتها المتدرجة وأفنيتها المبلطة وشرفاتها المطلة على الخليج.',
    wiki: ['en:Casbah of Algiers', "fr:Casbah d'Alger"],
    commonsCategory: 'Casbah of Algiers',
    commonsSearch: ['Casbah Algiers'],
  },
  {
    key: 'dz-alg-ketchaoua',
    city: 'Algiers', cat: 'religious_site', lat: 36.7846, lng: 3.0602, min: 45, radius: 80,
    en: 'Ketchaoua Mosque', fr: 'Mosquée Ketchaoua', ar: 'جامع كتشاوة',
    dEn: 'The Casbah\'s landmark mosque, built in 1612, made a cathedral under French rule and returned to worship in 1962.',
    dFr: "Mosquée emblématique de la Casbah, bâtie en 1612, transformée en cathédrale sous la colonisation puis rendue au culte en 1962.",
    dAr: 'جامع القصبة الشهير، بُني عام 1612، حُوّل إلى كاتدرائية إبان الاستعمار ثم أُعيد للصلاة سنة 1962.',
    wiki: ['en:Ketchaoua Mosque', 'fr:Mosquée Ketchaoua'],
    commonsCategory: 'Ketchaoua Mosque',
  },
  {
    key: 'dz-alg-djamaa-el-djazair',
    city: 'Algiers', cat: 'religious_site', lat: 36.7331, lng: 3.172, min: 90, radius: 250,
    en: 'Djamaa el Djazaïr', fr: "Grande Mosquée d'Alger", ar: 'جامع الجزائر',
    dEn: 'The third-largest mosque in the world, with a 265-metre minaret you can ride to the top of for the whole bay.',
    dFr: "Troisième plus grande mosquée du monde, dont le minaret de 265 mètres s'ouvre sur toute la baie d'Alger.",
    dAr: 'ثالث أكبر مسجد في العالم، بمئذنة يبلغ ارتفاعها 265 مترًا تطل على خليج الجزائر بأكمله.',
    wiki: ['en:Djamaa el Djazaïr', 'fr:Djamaâ El Djazaïr'],
    commonsCategory: 'Djamaa el Djazaïr',
    commonsSearch: ['Great Mosque of Algiers Djamaa el Djazair'],
  },
  {
    key: 'dz-alg-djamaa-el-kebir',
    city: 'Algiers', cat: 'religious_site', lat: 36.7841, lng: 3.0602, min: 40, radius: 70,
    en: 'Djamaa el Kebir', fr: "Grande Mosquée d'Alger (ancienne)", ar: 'الجامع الكبير',
    dEn: 'The oldest mosque still standing in Algiers, Almoravid in origin and barely changed since the eleventh century.',
    dFr: "La plus ancienne mosquée d'Alger encore debout, d'origine almoravide et presque inchangée depuis le XIe siècle.",
    dAr: 'أقدم مسجد قائم في الجزائر العاصمة، مرابطي الأصل ولم يتغير تقريبًا منذ القرن الحادي عشر.',
    wiki: ['en:Djamaa el Kebir', 'fr:Grande Mosquée d\'Alger'],
    commonsCategory: 'Djamaa el Kebir',
  },
  {
    key: 'dz-alg-djamaa-el-djedid',
    city: 'Algiers', cat: 'religious_site', lat: 36.7838, lng: 3.0608, min: 35, radius: 70,
    en: 'Djamaa el Djedid', fr: 'Mosquée de la Pêcherie', ar: 'الجامع الجديد',
    dEn: 'An Ottoman mosque of 1660 on the Place des Martyrs, its white dome the first thing seen from an arriving ship.',
    dFr: "Mosquée ottomane de 1660 sur la place des Martyrs, dont la coupole blanche accueille les navires à l'arrivée.",
    dAr: 'مسجد عثماني يعود لعام 1660 في ساحة الشهداء، قبته البيضاء أول ما يراه القادم من البحر.',
    wiki: ['en:Djamaa el Djedid', 'fr:Djamaa el Djedid'],
    commonsCategory: 'Djamaa el Djedid',
  },
  {
    key: 'dz-alg-notre-dame-afrique',
    city: 'Algiers', cat: 'religious_site', lat: 36.8003, lng: 3.0413, min: 50, radius: 120,
    en: "Notre-Dame d'Afrique", fr: "Basilique Notre-Dame d'Afrique", ar: 'كنيسة السيدة الإفريقية',
    dEn: 'A neo-Byzantine basilica on the cliff above Bologhine, facing the sea and inscribed "pray for us and for the Muslims".',
    dFr: "Basilique néo-byzantine sur la falaise de Bologhine, tournée vers la mer et portant l'inscription « priez pour nous et pour les musulmans ».",
    dAr: 'كاتدرائية بالطراز البيزنطي الجديد على جرف بولوغين، تطل على البحر وتحمل عبارة «صلّوا لأجلنا ولأجل المسلمين».',
    wiki: ["en:Notre-Dame d'Afrique", "fr:Basilique Notre-Dame d'Afrique"],
    commonsCategory: "Notre-Dame d'Afrique",
  },
  {
    key: 'dz-alg-maqam-echahid',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7457, lng: 3.0697, min: 60, radius: 150,
    en: 'Maqam Echahid', fr: 'Mémorial du Martyr', ar: 'مقام الشهيد',
    dEn: 'Three concrete palm fronds 92 metres high, raised in 1982 for the dead of the war of independence.',
    dFr: "Trois palmes de béton de 92 mètres, érigées en 1982 à la mémoire des morts de la guerre d'indépendance.",
    dAr: 'ثلاث سعفات نخيل خرسانية بارتفاع 92 مترًا، شُيدت عام 1982 تخليدًا لشهداء حرب التحرير.',
    wiki: ['en:Maqam Echahid', 'fr:Mémorial du Martyr'],
    commonsCategory: 'Maqam Echahid',
  },
  {
    key: 'dz-alg-jardin-essai',
    city: 'Algiers', cat: 'park_garden', lat: 36.7477, lng: 3.0761, min: 120, radius: 250,
    en: "Jardin d'Essai du Hamma", fr: "Jardin d'Essai du Hamma", ar: 'حديقة التجارب بالحامة',
    dEn: 'Thirty-two hectares of botanical garden laid out in 1832, with an avenue of dragon trees and a French formal parterre.',
    dFr: "Trente-deux hectares de jardin botanique dessinés en 1832, avec son allée de dracaenas et son parterre à la française.",
    dAr: 'اثنان وثلاثون هكتارًا من الحدائق النباتية أُنشئت عام 1832، بممرها الشهير من أشجار التنين وحديقتها الفرنسية.',
    hours: 'Tue–Sun 09:00–17:00',
    wiki: ["en:Jardin d'essai du Hamma", "fr:Jardin d'essai du Hamma"],
    commonsCategory: "Jardin d'essai du Hamma",
  },
  {
    key: 'dz-alg-bardo',
    city: 'Algiers', cat: 'museum', lat: 36.766, lng: 3.045, min: 75, radius: 80,
    en: 'Bardo National Museum', fr: 'Musée National du Bardo', ar: 'متحف الباردو الوطني',
    dEn: 'Prehistory and ethnography inside an eighteenth-century Ottoman villa, from Saharan rock art to Tuareg silver.',
    dFr: "Préhistoire et ethnographie dans une villa ottomane du XVIIIe siècle, de l'art rupestre saharien à l'argent touareg.",
    dAr: 'ما قبل التاريخ والإثنوغرافيا داخل فيلا عثمانية من القرن الثامن عشر، من الفن الصخري الصحراوي إلى فضة الطوارق.',
    hours: 'Sun–Thu 09:00–16:30',
    wiki: ['en:Bardo National Museum of Prehistory and Ethnography', 'fr:Musée national du Bardo (Alger)'],
    commonsCategory: 'Bardo National Museum (Algiers)',
    commonsSearch: ['Bardo National Museum Algiers'],
  },
  {
    key: 'dz-alg-beaux-arts',
    city: 'Algiers', cat: 'museum', lat: 36.7461, lng: 3.0723, min: 90, radius: 80,
    en: 'National Museum of Fine Arts', fr: 'Musée National des Beaux-Arts', ar: 'المتحف الوطني للفنون الجميلة',
    dEn: 'Africa\'s largest fine-art collection, eight thousand works stacked over five floors above the Jardin d\'Essai.',
    dFr: "La plus grande collection d'art d'Afrique : huit mille œuvres sur cinq niveaux, au-dessus du Jardin d'Essai.",
    dAr: 'أكبر مجموعة فنية في إفريقيا، ثمانية آلاف عمل موزعة على خمسة طوابق فوق حديقة التجارب.',
    hours: 'Sun–Thu 10:00–17:00',
    // Pinned: the en-wiki lead image is a fountain in the Jardin d'Essai next
    // door, not the museum.
    commonsFile: 'File:National Museum of Fine Arts of Algiers 01.jpg',
    wiki: ['en:National Museum of Fine Arts of Algiers', 'fr:Musée national des beaux-arts d\'Alger'],
    commonsCategory: 'National Museum of Fine Arts of Algiers',
  },
  {
    key: 'dz-alg-mama',
    city: 'Algiers', cat: 'museum', lat: 36.7773, lng: 3.0576, min: 60, radius: 60,
    en: 'MAMA — Museum of Modern Art', fr: "Musée d'Art Moderne d'Alger", ar: 'متحف الجزائر للفن الحديث',
    dEn: 'Contemporary Algerian and African art in a Neo-Moorish former department store on rue Larbi Ben M\'hidi.',
    dFr: "Art algérien et africain contemporain dans un ancien grand magasin néo-mauresque de la rue Larbi Ben M'hidi.",
    dAr: 'فن جزائري وإفريقي معاصر داخل متجر كبير سابق بالطراز المغاربي الجديد في شارع العربي بن مهيدي.',
    hours: 'Sat–Thu 10:00–18:00',
    wiki: ['en:Museum of Modern Art of Algiers', 'fr:Musée public national d\'art moderne et contemporain d\'Alger'],
    commonsCategory: 'Museum of Modern Art of Algiers',
  },
  {
    key: 'dz-alg-bastion-23',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7877, lng: 3.0563, min: 60, radius: 100,
    en: 'Bastion 23 — Palais des Raïs', fr: 'Bastion 23 — Palais des Raïs', ar: 'قصر الرياس - الحصن 23',
    dEn: 'Three Ottoman corsair palaces and a fisherman\'s house, the last surviving piece of the lower Casbah\'s sea front.',
    dFr: "Trois palais de raïs ottomans et une maison de pêcheurs, dernier fragment du front de mer de la basse Casbah.",
    dAr: 'ثلاثة قصور لرياس عثمانيين وبيت صياد، آخر ما تبقّى من الواجهة البحرية للقصبة السفلى.',
    wiki: ['en:Bastion 23', 'fr:Palais des Raïs'],
    commonsCategory: 'Palais des Raïs',
    commonsSearch: ['Bastion 23 Algiers'],
  },
  {
    key: 'dz-alg-antiquites',
    city: 'Algiers', cat: 'museum', lat: 36.7615, lng: 3.046, min: 70, radius: 70,
    en: 'National Museum of Antiquities', fr: 'Musée National des Antiquités', ar: 'المتحف الوطني للآثار',
    dEn: 'Roman mosaics, Punic steles and Islamic metalwork in Algeria\'s oldest museum, founded in 1838.',
    dFr: "Mosaïques romaines, stèles puniques et dinanderie islamique dans le plus ancien musée d'Algérie, fondé en 1838.",
    dAr: 'فسيفساء رومانية وأنصاب بونيقية ومشغولات إسلامية في أقدم متاحف الجزائر، تأسس عام 1838.',
    hours: 'Sun–Thu 09:00–16:00',
    wiki: ['en:National Museum of Antiquities (Algeria)', 'fr:Musée national des antiquités et des arts islamiques'],
    commonsCategory: 'National Museum of Antiquities (Algiers)',
    commonsSearch: ['Musée national des antiquités Alger'],
  },
  {
    key: 'dz-alg-tna',
    city: 'Algiers', cat: 'cultural_venue', lat: 36.7813, lng: 3.06, min: 45, radius: 60,
    en: 'Algerian National Theatre', fr: 'Théâtre National Algérien', ar: 'المسرح الوطني الجزائري',
    dEn: 'An 1853 Italianate opera house on Place Port Saïd, still the country\'s principal stage.',
    dFr: "Salle à l'italienne de 1853 sur la place Port-Saïd, toujours la première scène du pays.",
    dAr: 'مسرح على الطراز الإيطالي شُيد عام 1853 بساحة بور سعيد، ولا يزال أهم خشبة في البلاد.',
    wiki: ['en:Algerian National Theatre', 'fr:Théâtre national algérien Mahieddine-Bachtarzi'],
    commonsCategory: 'Théâtre national algérien Mahieddine Bachtarzi',
    commonsSearch: ['Algerian National Theatre Algiers'],
  },
  {
    key: 'dz-alg-grande-poste',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7742, lng: 3.0596, min: 30, radius: 80,
    en: 'Grande Poste d\'Alger', fr: "Grande Poste d'Alger", ar: 'البريد المركزي بالجزائر',
    dEn: 'The 1910 central post office, the high point of Neo-Moorish architecture and the city\'s default meeting spot.',
    dFr: "La poste centrale de 1910, sommet du style néo-mauresque et point de rendez-vous par défaut des Algérois.",
    dAr: 'مبنى البريد المركزي المشيد عام 1910، ذروة الطراز المغاربي الجديد ومكان اللقاء المعتاد لسكان العاصمة.',
    wiki: ['fr:Grande Poste d\'Alger', 'en:Grande Poste d\'Alger'],
    commonsCategory: 'Grande Poste (Algiers)',
    commonsSearch: ['Grande Poste Alger'],
  },
  {
    key: 'dz-alg-place-martyrs',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7846, lng: 3.0603, min: 30, radius: 120,
    en: 'Place des Martyrs', fr: 'Place des Martyrs', ar: 'ساحة الشهداء',
    dEn: 'The square at the foot of the Casbah, with an Ottoman and Roman excavation displayed inside the metro station below.',
    dFr: "La place au pied de la Casbah, dont les fouilles ottomanes et romaines sont exposées dans la station de métro en dessous.",
    dAr: 'الساحة الواقعة أسفل القصبة، وتُعرض حفرياتها العثمانية والرومانية داخل محطة المترو تحتها.',
    wiki: ['fr:Place des Martyrs (Alger)'],
    commonsCategory: 'Place des Martyrs (Algiers)',
    commonsSearch: ['Place des Martyrs Alger'],
  },
  {
    key: 'dz-alg-citadelle',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7845, lng: 3.0551, min: 60, radius: 120,
    en: 'Citadel of Algiers', fr: 'Citadelle d\'Alger', ar: 'قلعة الجزائر',
    dEn: 'The Dey\'s fortress crowning the Casbah, where the fan-blow of 1827 gave France its pretext for invasion.',
    dFr: "La forteresse du Dey au sommet de la Casbah, où le coup d'éventail de 1827 offrit à la France son prétexte.",
    dAr: 'قلعة الداي في أعلى القصبة، حيث وقعت حادثة المروحة عام 1827 التي اتخذتها فرنسا ذريعة للغزو.',
    wiki: ['en:Citadel of Algiers', 'fr:Citadelle d\'Alger'],
    commonsCategory: 'Citadel of Algiers',
  },
  {
    key: 'dz-alg-dar-hassan-pacha',
    city: 'Algiers', cat: 'historical_monument', lat: 36.7848, lng: 3.06, min: 40, radius: 60,
    en: 'Dar Hassan Pacha', fr: 'Dar Hassan Pacha', ar: 'دار حسن باشا',
    dEn: 'A 1791 Ottoman palace of galleried courtyards, later the winter residence of the French governors-general.',
    dFr: "Palais ottoman de 1791 aux patios à galeries, devenu résidence d'hiver des gouverneurs généraux français.",
    dAr: 'قصر عثماني يعود لعام 1791 بأفنيته ذات الأروقة، صار لاحقًا المقر الشتوي للحكام العامين الفرنسيين.',
    wiki: ['fr:Dar Hassan Pacha', 'en:Dar Hassan Pacha'],
    commonsCategory: 'Dar Hassan Pacha',
    commonsSearch: ['Dar Hassan Pacha Algiers'],
  },
  {
    key: 'dz-alg-dar-aziza',
    city: 'Algiers', cat: 'historical_monument', lat: 36.785, lng: 3.0603, min: 35, radius: 60,
    en: 'Dar Aziza', fr: 'Dar Aziza', ar: 'دار عزيزة',
    dEn: 'A sixteenth-century palace beside Ketchaoua, its arcaded patio the textbook example of Algerine domestic architecture.',
    dFr: "Palais du XVIe siècle voisin de Ketchaoua, dont le patio à arcades est l'exemple canonique de la maison algéroise.",
    dAr: 'قصر من القرن السادس عشر بجوار جامع كتشاوة، فناؤه المقنطر نموذج مرجعي للعمارة السكنية الجزائرية.',
    wiki: ['fr:Dar Aziza', 'en:Dar Aziza'],
    commonsCategory: 'Dar Aziza',
    commonsSearch: ['Dar Aziza Algiers palace'],
  },
  {
    key: 'dz-alg-sidi-abderrahmane',
    city: 'Algiers', cat: 'religious_site', lat: 36.7861, lng: 3.057, min: 35, radius: 60,
    en: 'Sidi Abderrahmane Mosque', fr: 'Mosquée Sidi Abderrahmane', ar: 'جامع سيدي عبد الرحمن',
    dEn: 'The mausoleum-mosque of the city\'s patron saint, set in a walled garden of cypresses inside the upper Casbah.',
    dFr: "Mosquée-mausolée du saint patron de la ville, dans un jardin clos de cyprès au cœur de la haute Casbah.",
    dAr: 'مسجد وضريح شفيع المدينة، وسط حديقة مسوّرة من أشجار السرو في أعالي القصبة.',
    wiki: ['fr:Mosquée Sidi Abderrahmane', 'en:Sidi Abderrahmane Mosque'],
    commonsCategory: 'Sidi Abderrahmane Mosque',
    commonsSearch: ['Sidi Abderrahmane Algiers mosque'],
  },
  {
    key: 'dz-alg-arts-traditions',
    city: 'Algiers', cat: 'museum', lat: 36.7867, lng: 3.0609, min: 50, radius: 50,
    en: 'Museum of Popular Arts and Traditions', fr: 'Musée des Arts et Traditions Populaires', ar: 'متحف الفنون والتقاليد الشعبية',
    dEn: 'Costume, jewellery and woodwork in Dar Khedaoudj el Amia, a merchant\'s house of 1570 in the heart of the Casbah.',
    dFr: "Costumes, bijoux et boiseries dans Dar Khedaoudj el Amia, maison de marchand de 1570 au cœur de la Casbah.",
    dAr: 'أزياء وحلي وأشغال خشبية في دار خديجة العمياء، بيت تاجر يعود لعام 1570 في قلب القصبة.',
    hours: 'Sun–Thu 09:00–16:00',
    wiki: ['fr:Musée national des arts et traditions populaires (Alger)'],
    commonsCategory: 'Dar Khedaoudj el Amia',
    commonsSearch: ['Dar Khedaoudj el Amia Algiers', 'Musée des arts et traditions populaires Alger'],
  },
  {
    key: 'dz-alg-villa-abdeltif',
    city: 'Algiers', cat: 'cultural_venue', lat: 36.7447, lng: 3.0731, min: 45, radius: 70,
    en: 'Villa Abd-el-Tif', fr: 'Villa Abd-el-Tif', ar: 'فيلا عبد اللطيف',
    dEn: 'An Ottoman country house above the Jardin d\'Essai that housed a residency for French painters from 1907.',
    dFr: "Maison de campagne ottomane dominant le Jardin d'Essai, résidence de peintres français à partir de 1907.",
    dAr: 'منزل ريفي عثماني يعلو حديقة التجارب، احتضن إقامة فنية للرسامين الفرنسيين منذ عام 1907.',
    wiki: ['fr:Villa Abd-el-Tif', 'en:Villa Abd-el-Tif'],
    commonsCategory: 'Villa Abd-el-Tif',
    commonsSearch: ['Villa Abd-el-Tif Alger'],
  },
  {
    key: 'dz-alg-riadh-el-feth',
    city: 'Algiers', cat: 'cultural_venue', lat: 36.7448, lng: 3.0705, min: 75, radius: 120,
    en: 'Riadh El Feth', fr: 'Riadh El Feth', ar: 'رياض الفتح',
    dEn: 'The terraced arts and shopping complex under the Martyrs\' Memorial, with galleries and a terrace over the bay.',
    dFr: "Complexe culturel et commercial en terrasses sous le Mémorial du Martyr, avec galeries et vue sur la baie.",
    dAr: 'مركب ثقافي وتجاري مدرج أسفل مقام الشهيد، يضم أروقة فنية وشرفة تطل على الخليج.',
    wiki: ['fr:Riadh El Feth', 'en:Riadh El Feth'],
    commonsCategory: 'Riadh El Feth',
    commonsSearch: ['Riadh El Feth Alger'],
  },
  {
    key: 'dz-alg-moudjahid',
    city: 'Algiers', cat: 'museum', lat: 36.7452, lng: 3.07, min: 60, radius: 70,
    en: 'National Museum of the Mujahid', fr: 'Musée National du Moudjahid', ar: 'المتحف الوطني للمجاهد',
    dEn: 'The war of independence told through weapons, photographs and prison letters, beneath the Martyrs\' Memorial.',
    dFr: "La guerre d'indépendance racontée par les armes, les photographies et les lettres de prison, sous le Mémorial du Martyr.",
    dAr: 'حرب التحرير مروية عبر الأسلحة والصور ورسائل السجون، أسفل مقام الشهيد.',
    hours: 'Sat–Thu 09:00–17:00',
    // Pinned: the search kept returning single exhibits (a martyr's wristwatch)
    // rather than the museum, which makes a poor establishing photo.
    commonsFile: 'File:Musée national du moudjahid 1.jpg',
    wiki: ['fr:Musée national du Moudjahid'],
    commonsCategory: 'Musée national du Moudjahid',
    commonsSearch: ['Musée du Moudjahid Alger', 'Maqam Echahid museum'],
  },
  {
    key: 'dz-alg-jardin-prague',
    city: 'Algiers', cat: 'park_garden', lat: 36.7892, lng: 3.0588, min: 30, radius: 90,
    en: 'Prague Garden', fr: 'Jardin de Prague', ar: 'حديقة براغ',
    dEn: 'A terraced garden above Bab El Oued, formerly Marengo, looking down on Notre-Dame d\'Afrique.',
    dFr: "Jardin en terrasses au-dessus de Bab El Oued, ancien Marengo, dominant Notre-Dame d'Afrique.",
    dAr: 'حديقة مدرجة فوق باب الوادي، كانت تُسمى مارينغو، تطل على كنيسة السيدة الإفريقية.',
    wiki: ['fr:Jardin de Prague'],
    commonsCategory: 'Jardin Marengo',
    commonsSearch: ['Jardin de Prague Alger', 'Marengo garden Algiers'],
  },
  {
    key: 'dz-alg-sablettes',
    city: 'Algiers', cat: 'beach', lat: 36.744, lng: 3.1174, min: 90, radius: 300,
    en: 'Les Sablettes', fr: 'Plage des Sablettes', ar: 'شاطئ السابلات',
    dEn: 'A reclaimed two-kilometre seafront promenade and beach east of the port, busiest at sunset.',
    dFr: "Deux kilomètres de promenade et de plage gagnés sur la mer à l'est du port, animés au coucher du soleil.",
    dAr: 'كيلومتران من الممشى والشاطئ المستصلحين شرق الميناء، يزدحمان عند الغروب.',
    wiki: ['fr:Les Sablettes (Alger)'],
    commonsCategory: 'Sablettes (Algiers)',
    commonsSearch: ['Sablettes Alger plage', 'Les Sablettes Algiers promenade'],
  },
  // Stands in for El Kettani, which was the first choice on the ground but has
  // no photograph anywhere on Commons — the cascade could only offer a picture
  // of the hospital up the road. A beach in the same wilaya that can actually
  // be shown beats a better beach rendered as a grey box.
  {
    key: 'dz-alg-palm-beach',
    city: 'Algiers', cat: 'beach', lat: 36.7561, lng: 2.8797, min: 90, radius: 250,
    en: 'Palm Beach, Staoueli', fr: 'Palm Beach (Staoueli)', ar: 'شاطئ النخيل بسطاوالي',
    dEn: 'A pine-backed sand beach on the western corniche, the calmest of the capital\'s swimming beaches.',
    dFr: "Plage de sable adossée aux pins sur la corniche ouest, la plus calme des plages de baignade de la capitale.",
    dAr: 'شاطئ رملي تحيط به أشجار الصنوبر على الكورنيش الغربي، أهدأ شواطئ العاصمة للسباحة.',
    commonsFile: 'File:Palm Beach شاطئ النخيل - panoramio.jpg',
    commonsSearch: ['Palm Beach Staoueli Alger'],
  },

  // ===========================================================================
  // ORAN
  // ===========================================================================
  {
    key: 'dz-orn-santa-cruz',
    city: 'Oran', cat: 'historical_monument', lat: 35.7092, lng: -0.665, min: 75, radius: 150,
    en: 'Fort Santa Cruz', fr: 'Fort de Santa Cruz', ar: 'حصن سانتا كروز',
    dEn: 'A Spanish fortress of 1577 on the shoulder of Murdjadjo, four hundred metres straight above the harbour.',
    dFr: "Forteresse espagnole de 1577 accrochée au Murdjadjo, à quatre cents mètres à l'aplomb du port.",
    dAr: 'حصن إسباني يعود لعام 1577 على سفح جبل مرجاجو، على ارتفاع أربعمائة متر فوق الميناء.',
    wiki: ['en:Fort of Santa Cruz', 'fr:Fort de Santa Cruz'],
    commonsCategory: 'Fort Santa Cruz (Oran)',
    commonsSearch: ['Fort Santa Cruz Oran'],
  },
  {
    key: 'dz-orn-chapelle-santa-cruz',
    city: 'Oran', cat: 'religious_site', lat: 35.7055, lng: -0.6555, min: 40, radius: 100,
    en: 'Chapel of Santa Cruz', fr: 'Chapelle de Santa Cruz', ar: 'كنيسة سانتا كروز',
    dEn: 'A votive chapel raised in 1849 after the cholera lifted, on the ridge below the fort.',
    dFr: "Chapelle votive élevée en 1849 après la fin du choléra, sur la crête au-dessous du fort.",
    dAr: 'كنيسة نذرية شُيدت عام 1849 بعد انحسار وباء الكوليرا، على الحافة أسفل الحصن.',
    wiki: ['fr:Chapelle Santa Cruz', 'en:Santa Cruz Chapel'],
    commonsCategory: 'Chapelle Santa Cruz (Oran)',
    commonsSearch: ['Chapelle Santa Cruz Oran'],
  },
  {
    key: 'dz-orn-murdjadjo',
    city: 'Oran', cat: 'viewpoint', lat: 35.7089, lng: -0.6674, min: 60, radius: 400,
    en: 'Murdjadjo', fr: 'Murdjadjo', ar: 'جبل مرجاجو',
    dEn: 'The mountain that shelters Oran, with the whole gulf and Mers el-Kébir laid out from the crest road.',
    dFr: "La montagne qui abrite Oran : depuis la route de crête, tout le golfe et Mers el-Kébir s'étalent.",
    dAr: 'الجبل الذي يحتضن وهران، ومن طريق قمته يمتد الخليج بأكمله والمرسى الكبير.',
    wiki: ['en:Murdjadjo', 'fr:Murdjadjo'],
    commonsCategory: 'Murdjadjo',
  },
  {
    key: 'dz-orn-palais-bey',
    city: 'Oran', cat: 'historical_monument', lat: 35.7057, lng: -0.6493, min: 60, radius: 90,
    en: 'Palace of the Bey', fr: 'Palais du Bey', ar: 'قصر الباي',
    dEn: 'The residence built for Bey Mohamed el-Kebir after he took Oran back from Spain in 1792.',
    dFr: "La résidence bâtie pour le bey Mohamed el-Kébir après la reprise d'Oran aux Espagnols en 1792.",
    dAr: 'المقر الذي بُني للباي محمد الكبير بعد استرجاعه وهران من الإسبان عام 1792.',
    // Pinned: the fr-wiki lead image is a file titled simply "الحديقة" ("the
    // garden") that shows no identifiable part of the palace.
    commonsFile: 'File:The Bey’s Palace of Oran 6.jpg',
    wiki: ['fr:Palais du Bey (Oran)', 'en:Bey Palace of Oran'],
    commonsCategory: 'Palais du Bey (Oran)',
    commonsSearch: ['Palais du Bey Oran'],
  },
  {
    key: 'dz-orn-mosquee-pacha',
    city: 'Oran', cat: 'religious_site', lat: 35.695, lng: -0.638, min: 35, radius: 60,
    en: 'Pasha Mosque', fr: 'Mosquée du Pacha', ar: 'مسجد الباشا',
    dEn: 'Oran\'s oldest working mosque, paid for in 1796 out of the ransom of Spanish prisoners.',
    dFr: "La plus ancienne mosquée en activité d'Oran, financée en 1796 par la rançon des prisonniers espagnols.",
    dAr: 'أقدم مسجد عامل في وهران، مُوّل عام 1796 من فدية الأسرى الإسبان.',
    wiki: ['fr:Mosquée du Pacha', 'en:Pasha Mosque (Oran)'],
    commonsCategory: 'Mosquée du Pacha (Oran)',
    commonsSearch: ['Mosquée du Pacha Oran'],
  },
  {
    key: 'dz-orn-ben-salem',
    city: 'Oran', cat: 'religious_site', lat: 35.7, lng: -0.65, min: 35, radius: 60,
    en: 'Abdellah Ben Salem Mosque', fr: 'Mosquée Abdellah Ben Salem', ar: 'مسجد عبد الله بن سالم',
    dEn: 'Built in 1880 as the Great Synagogue of Oran, one of North Africa\'s largest, and a mosque since 1975.',
    dFr: "Édifiée en 1880 comme grande synagogue d'Oran, l'une des plus vastes d'Afrique du Nord, mosquée depuis 1975.",
    dAr: 'شُيد عام 1880 ككنيس وهران الكبير، أحد أكبر كنس شمال إفريقيا، وتحوّل مسجدًا منذ 1975.',
    wiki: ['en:Great Synagogue of Oran', 'fr:Grande synagogue d\'Oran'],
    commonsCategory: 'Great Synagogue of Oran',
    commonsSearch: ['Abdellah Ben Salem Mosque Oran'],
  },
  {
    key: 'dz-orn-zabana',
    city: 'Oran', cat: 'museum', lat: 35.6958, lng: -0.645, min: 75, radius: 70,
    en: 'Ahmed Zabana National Museum', fr: 'Musée National Ahmed Zabana', ar: 'متحف أحمد زبانة الوطني',
    dEn: 'Oran\'s general museum since 1935: prehistory, Roman finds, natural history and a fine-art wing.',
    dFr: "Le musée généraliste d'Oran depuis 1935 : préhistoire, antiquités romaines, histoire naturelle et beaux-arts.",
    dAr: 'المتحف العام لوهران منذ 1935: ما قبل التاريخ، آثار رومانية، تاريخ طبيعي وجناح للفنون الجميلة.',
    hours: 'Sat–Thu 09:00–16:30',
    wiki: ['en:Ahmed Zabana National Museum', 'fr:Musée national Ahmed-Zabana'],
    commonsCategory: 'Musée national Ahmed Zabana',
    commonsSearch: ['Ahmed Zabana museum Oran'],
  },
  {
    key: 'dz-orn-theatre',
    city: 'Oran', cat: 'cultural_venue', lat: 35.6975, lng: -0.6365, min: 45, radius: 60,
    en: 'Oran Regional Theatre', fr: "Théâtre Régional d'Oran", ar: 'المسرح الجهوي لوهران',
    dEn: 'A 1907 municipal theatre on Place du 1er Novembre, named for the playwright Abdelkader Alloula.',
    dFr: "Théâtre municipal de 1907 sur la place du 1er-Novembre, baptisé du nom du dramaturge Abdelkader Alloula.",
    dAr: 'مسرح بلدي شُيد عام 1907 بساحة أول نوفمبر، يحمل اسم الكاتب المسرحي عبد القادر علولة.',
    wiki: ['en:Oran Regional Theatre', 'fr:Théâtre régional d\'Oran'],
    commonsCategory: 'Théâtre régional d\'Oran',
    commonsSearch: ['Regional Theatre of Oran'],
  },
  {
    key: 'dz-orn-place-1er-novembre',
    city: 'Oran', cat: 'historical_monument', lat: 35.6968, lng: -0.6355, min: 30, radius: 100,
    en: 'Place du 1er Novembre', fr: 'Place du 1er Novembre 1954', ar: 'ساحة أول نوفمبر 1954',
    dEn: 'The city\'s central square, ringed by the theatre and town hall around an 1898 marble obelisk.',
    dFr: "La place centrale, cernée par le théâtre et l'hôtel de ville autour d'un obélisque de marbre de 1898.",
    dAr: 'الساحة المركزية للمدينة، يحيط بها المسرح والبلدية حول مسلة رخامية تعود لعام 1898.',
    wiki: ['fr:Place du 1er-Novembre-1954 (Oran)'],
    commonsCategory: 'Place du 1er Novembre 1954 (Oran)',
    commonsSearch: ['Place du 1er Novembre Oran'],
  },
  {
    key: 'dz-orn-cathedrale',
    city: 'Oran', cat: 'cultural_venue', lat: 35.697, lng: -0.634, min: 40, radius: 60,
    en: 'Sacred Heart Cathedral', fr: 'Cathédrale du Sacré-Cœur', ar: 'كاتدرائية القلب المقدس',
    dEn: 'A vast Neo-Byzantine cathedral of 1913, deconsecrated in 1984 and now the city\'s public library.',
    dFr: "Immense cathédrale néo-byzantine de 1913, désaffectée en 1984 et devenue la bibliothèque municipale.",
    dAr: 'كاتدرائية ضخمة بالطراز البيزنطي الجديد شُيدت عام 1913، أُغلقت عام 1984 وصارت المكتبة البلدية.',
    wiki: ['en:Sacred Heart Cathedral, Oran', 'fr:Cathédrale du Sacré-Cœur d\'Oran'],
    commonsCategory: 'Cathédrale du Sacré-Cœur d\'Oran',
    commonsSearch: ['Sacred Heart Cathedral Oran'],
  },
  {
    key: 'dz-orn-chateau-neuf',
    city: 'Oran', cat: 'historical_monument', lat: 35.701, lng: -0.644, min: 45, radius: 100,
    en: 'Château Neuf', fr: 'Château Neuf', ar: 'القصر الجديد',
    dEn: 'The Spanish citadel of 1563 above Sidi El Houari, later the seat of the beys and of French command.',
    dFr: "Citadelle espagnole de 1563 dominant Sidi El Houari, plus tard siège des beys puis du commandement français.",
    dAr: 'قلعة إسبانية تعود لعام 1563 تعلو سيدي الهواري، صارت لاحقًا مقرًا للبايات ثم للقيادة الفرنسية.',
    wiki: ['fr:Château-Neuf (Oran)', 'en:Château Neuf (Oran)'],
    commonsCategory: 'Château-Neuf (Oran)',
    commonsSearch: ['Chateau neuf Oran Algerie'],
  },
  {
    key: 'dz-orn-fort-lamoune',
    city: 'Oran', cat: 'historical_monument', lat: 35.7136, lng: -0.6565, min: 40, radius: 90,
    en: 'Fort Lamoune', fr: 'Fort Lamoune', ar: 'حصن لامون',
    dEn: 'A sea-level Spanish bastion guarding the western approach to the old harbour.',
    dFr: "Bastion espagnol au ras de l'eau, gardant l'accès occidental au vieux port.",
    dAr: 'حصن إسباني على مستوى البحر يحرس المدخل الغربي للميناء القديم.',
    wiki: ['fr:Fort Lamoune'],
    commonsCategory: 'Fort Lamoune',
    commonsSearch: ['Fort Lamoune Oran'],
  },
  {
    key: 'dz-orn-mers-el-kebir',
    city: 'Oran', cat: 'historical_monument', lat: 35.7376, lng: -0.6994, min: 60, radius: 250,
    en: 'Mers el-Kébir', fr: 'Mers el-Kébir', ar: 'المرسى الكبير',
    dEn: 'The great natural harbour west of Oran, fortified since antiquity and known for the naval action of 1940.',
    dFr: "Le grand port naturel à l'ouest d'Oran, fortifié depuis l'Antiquité et connu pour l'affaire navale de 1940.",
    dAr: 'الميناء الطبيعي الكبير غرب وهران، محصّن منذ العصور القديمة ومعروف بمعركته البحرية عام 1940.',
    // Pinned: the article's lead image is a Murdjadjo panorama already used by
    // the Murdjadjo entry, so the two POIs showed the same photograph.
    commonsFile: 'File:Mers El Kébir – Strategic Naval Port and Historic Site on the Algerian Coast 1.jpg',
    wiki: ['en:Mers El Kébir', 'fr:Mers el-Kébir'],
    commonsCategory: 'Mers El Kébir',
  },
  {
    key: 'dz-orn-andalouses',
    city: 'Oran', cat: 'beach', lat: 35.7597, lng: -0.8281, min: 120, radius: 350,
    en: 'Les Andalouses', fr: 'Les Andalouses', ar: 'شاطئ الأندلسيات',
    dEn: 'A long sand beach twenty-five kilometres west of the city, sheltered under the Murdjadjo foothills.',
    dFr: "Longue plage de sable à vingt-cinq kilomètres à l'ouest, abritée au pied du Murdjadjo.",
    dAr: 'شاطئ رملي طويل على بعد خمسة وعشرين كيلومترًا غرب المدينة، في حماية سفوح مرجاجو.',
    wiki: ['fr:Les Andalouses', 'en:Les Andalouses'],
    commonsCategory: 'Les Andalouses',
    commonsSearch: ['Les Andalouses beach Oran'],
  },
  {
    key: 'dz-orn-ain-el-turk',
    city: 'Oran', cat: 'beach', lat: 35.7431, lng: -0.7683, min: 100, radius: 350,
    en: 'Aïn El Turk', fr: 'Aïn El Turk', ar: 'عين الترك',
    dEn: 'The seaside town on the corniche west of Oran, and the busiest stretch of coast in the wilaya.',
    dFr: "La station balnéaire de la corniche à l'ouest d'Oran, portion de côte la plus fréquentée de la wilaya.",
    dAr: 'مدينة ساحلية على الكورنيش غرب وهران، وأكثر شواطئ الولاية ازدحامًا.',
    wiki: ['en:Aïn El Turk', 'fr:Aïn El Turk'],
    commonsCategory: 'Aïn El Turk',
  },
  {
    key: 'dz-orn-front-de-mer',
    city: 'Oran', cat: 'park_garden', lat: 35.699, lng: -0.629, min: 45, radius: 200,
    en: 'Promenade de Létang', fr: 'Promenade de Létang', ar: 'ممشى ليتانغ',
    dEn: 'The balcony boulevard above the port, laid out in the 1840s and still Oran\'s evening walk.',
    dFr: "Le boulevard-balcon au-dessus du port, tracé dans les années 1840 et toujours la promenade du soir.",
    dAr: 'الجادة المطلة على الميناء، شُقّت في أربعينيات القرن التاسع عشر ولا تزال ممشى المساء في وهران.',
    wiki: ['fr:Promenade de Létang'],
    commonsCategory: 'Promenade de Létang',
    commonsSearch: ['Promenade de Létang Oran', 'Front de mer Oran'],
  },
  {
    key: 'dz-orn-medina-jdida',
    city: 'Oran', cat: 'historical_monument', lat: 35.6955, lng: -0.6473, min: 60, radius: 250,
    en: 'Medina Jdida', fr: 'Medina Jdida', ar: 'المدينة الجديدة',
    dEn: 'The "new town" of 1845, built for Oran\'s Muslim population and still the city\'s trading quarter.',
    dFr: "La « ville nouvelle » de 1845, bâtie pour la population musulmane d'Oran et toujours son quartier commerçant.",
    dAr: '«المدينة الجديدة» المشيدة عام 1845 لسكان وهران المسلمين، ولا تزال حيّها التجاري.',
    wiki: ['fr:Médina Jdida', 'en:Medina Jdida'],
    commonsCategory: 'Medina Jdida',
    commonsSearch: ['Medina Jdida Oran'],
  },
  {
    key: 'dz-orn-sidi-el-houari',
    city: 'Oran', cat: 'historical_monument', lat: 35.7013, lng: -0.6488, min: 75, radius: 250,
    en: 'Sidi El Houari', fr: 'Sidi El Houari', ar: 'سيدي الهواري',
    dEn: 'Oran\'s founding quarter beneath the Château Neuf, with Ottoman baths, the Pasha mosque and Spanish walls.',
    dFr: "Le quartier fondateur d'Oran sous le Château-Neuf : bains ottomans, mosquée du Pacha et murailles espagnoles.",
    dAr: 'الحي المؤسس لوهران أسفل القصر الجديد، بحماماته العثمانية ومسجد الباشا وأسواره الإسبانية.',
    wiki: ['fr:Sidi El Houari', 'en:Sidi El Houari'],
    commonsCategory: 'Sidi El Houari',
    commonsSearch: ['Sidi El Houari Oran'],
  },
  {
    key: 'dz-orn-santon',
    city: 'Oran', cat: 'viewpoint', lat: 35.7347, lng: -0.7119, min: 45, radius: 150,
    en: 'Djebel Santon', fr: 'Djebel Santon', ar: 'جبل سانتون',
    dEn: 'A hilltop fort over Mers el-Kébir, the best single view of the bay and the naval base below.',
    dFr: "Fort de sommet dominant Mers el-Kébir, la plus belle vue d'ensemble sur la baie et la base navale.",
    dAr: 'حصن على قمة تطل على المرسى الكبير، وأجمل إطلالة على الخليج والقاعدة البحرية أسفله.',
    wiki: ['fr:Djebel Santon'],
    commonsCategory: 'Djebel Santon',
    commonsSearch: ['Djebel Santon Oran', 'Fort Santon Oran'],
  },
  {
    key: 'dz-orn-gambetta',
    city: 'Oran', cat: 'historical_monument', lat: 35.7069, lng: -0.6215, min: 30, radius: 120,
    en: 'Gambetta', fr: 'Gambetta', ar: 'قمبيطة',
    dEn: 'A colonial-era district of wide avenues and 1930s facades on the eastern plateau above the port.',
    dFr: "Quartier colonial aux larges avenues et façades des années 1930, sur le plateau est au-dessus du port.",
    dAr: 'حي من الحقبة الاستعمارية بجاداته الواسعة وواجهاته من الثلاثينيات، على الهضبة الشرقية فوق الميناء.',
    // Pinned: "Gambetta Oran" as a text search matches a 1942 War Office street
    // plan of the city before it matches any photograph of the district.
    commonsFile: 'File:Gambetta rond point Oran Algérie.jpg',
    wiki: ['fr:Gambetta (Oran)'],
    commonsCategory: 'Gambetta (Oran)',
    commonsSearch: ['Gambetta rond point Oran'],
  },

  // ===========================================================================
  // CONSTANTINE
  // ===========================================================================
  {
    key: 'dz-cst-sidi-mcid',
    city: 'Constantine', cat: 'historical_monument', lat: 36.371, lng: 6.613, min: 45, radius: 120,
    en: "Sidi M'Cid Bridge", fr: "Pont de Sidi M'Cid", ar: 'جسر سيدي مسيد',
    dEn: 'A suspension bridge of 1912 slung 175 metres above the Rhumel — the highest in the world when it opened.',
    dFr: "Pont suspendu de 1912 à 175 mètres au-dessus du Rhumel : le plus haut du monde à son inauguration.",
    dAr: 'جسر معلق يعود لعام 1912 على ارتفاع 175 مترًا فوق وادي الرمال، كان الأعلى في العالم عند افتتاحه.',
    wiki: ["en:Sidi M'Cid Bridge", "fr:Pont de Sidi M'Cid"],
    commonsCategory: "Sidi M'Cid Bridge",
  },
  {
    key: 'dz-cst-ahmed-bey',
    city: 'Constantine', cat: 'historical_monument', lat: 36.3635, lng: 6.614, min: 90, radius: 90,
    en: 'Palace of Ahmed Bey', fr: 'Palais Ahmed Bey', ar: 'قصر أحمد باي',
    dEn: 'The last bey\'s residence, finished in 1835: painted galleries, marble courts and orange gardens.',
    dFr: "La résidence du dernier bey, achevée en 1835 : galeries peintes, cours de marbre et jardins d'orangers.",
    dAr: 'مقر آخر بايات قسنطينة، اكتمل عام 1835: أروقة مزخرفة وأفنية رخامية وحدائق برتقال.',
    hours: 'Sat–Thu 09:00–16:30',
    wiki: ['en:Ahmed Bey Palace', 'fr:Palais du Bey (Constantine)'],
    commonsCategory: 'Palais Ahmed Bey',
    commonsSearch: ['Palais Ahmed Bey Constantine'],
  },
  {
    key: 'dz-cst-emir-abdelkader',
    city: 'Constantine', cat: 'religious_site', lat: 36.36, lng: 6.62, min: 60, radius: 150,
    en: 'Emir Abdelkader Mosque', fr: 'Mosquée Emir Abdelkader', ar: 'مسجد الأمير عبد القادر',
    dEn: 'One of North Africa\'s largest mosques, opened in 1994, its twin minarets rising 107 metres over the plateau.',
    dFr: "L'une des plus grandes mosquées d'Afrique du Nord, ouverte en 1994, ses deux minarets culminant à 107 mètres.",
    dAr: 'أحد أكبر مساجد شمال إفريقيا، افتُتح عام 1994، وترتفع مئذنتاه التوأمان إلى 107 أمتار.',
    wiki: ['en:Emir Abdelkader Mosque', 'fr:Mosquée Émir-Abdelkader'],
    commonsCategory: 'Emir Abdelkader Mosque',
  },
  {
    key: 'dz-cst-cirta',
    city: 'Constantine', cat: 'museum', lat: 36.368, lng: 6.611, min: 75, radius: 70,
    en: 'Cirta National Museum', fr: 'Musée National Cirta', ar: 'متحف سيرتا الوطني',
    dEn: 'Numidian and Roman antiquities from the Constantine plateau, in a 1931 building above the Brèche.',
    dFr: "Antiquités numides et romaines du plateau constantinois, dans un bâtiment de 1931 au-dessus de la Brèche.",
    dAr: 'آثار نوميدية ورومانية من هضبة قسنطينة، داخل مبنى يعود لعام 1931 فوق ساحة البريش.',
    hours: 'Sat–Thu 09:00–16:30',
    wiki: ['en:Cirta National Museum', 'fr:Musée national Cirta'],
    commonsCategory: 'Musée national Cirta',
    commonsSearch: ['Cirta museum Constantine'],
  },
  {
    key: 'dz-cst-rhumel',
    city: 'Constantine', cat: 'viewpoint', lat: 36.3665, lng: 6.6155, min: 60, radius: 200,
    en: 'Rhumel Gorges', fr: 'Gorges du Rhumel', ar: 'أخاديد وادي الرمال',
    dEn: 'The limestone chasm that severs the city, two hundred metres deep and crossed by six bridges.',
    dFr: "La faille calcaire qui tranche la ville, deux cents mètres de profondeur et six ponts pour la franchir.",
    dAr: 'الأخدود الكلسي الذي يشق المدينة، بعمق مائتي متر وتعبره ستة جسور.',
    wiki: ['fr:Gorges du Rhumel', 'en:Rhumel'],
    commonsCategory: 'Gorges du Rhumel',
    commonsSearch: ['Rhumel gorge Constantine'],
  },
  {
    key: 'dz-cst-mellah-slimane',
    city: 'Constantine', cat: 'historical_monument', lat: 36.365, lng: 6.617, min: 30, radius: 80,
    en: "Mellah Slimane Footbridge", fr: 'Passerelle Mellah Slimane', ar: 'جسر ملاح سليمان',
    dEn: 'A 125-metre pedestrian suspension bridge of 1917, the shortcut between the old town and the station.',
    dFr: "Passerelle suspendue piétonne de 125 mètres, ouverte en 1917, raccourci entre la vieille ville et la gare.",
    dAr: 'جسر مشاة معلق بطول 125 مترًا افتُتح عام 1917، وهو الطريق المختصر بين المدينة القديمة والمحطة.',
    wiki: ['fr:Passerelle Perrégaux', 'en:Mellah Slimane Bridge'],
    commonsCategory: 'Passerelle Mellah Slimane',
    commonsSearch: ['Mellah Slimane bridge Constantine', 'Passerelle Perrégaux Constantine'],
  },
  {
    key: 'dz-cst-sidi-rached',
    city: 'Constantine', cat: 'historical_monument', lat: 36.363, lng: 6.612, min: 40, radius: 120,
    en: 'Sidi Rached Viaduct', fr: 'Viaduc de Sidi Rached', ar: 'جسر سيدي راشد',
    dEn: 'A masonry viaduct of 1912 on twenty-seven arches, the largest stone bridge of its kind ever built.',
    dFr: "Viaduc en maçonnerie de 1912 à vingt-sept arches, le plus grand pont de pierre de ce type jamais construit.",
    dAr: 'جسر حجري يعود لعام 1912 قائم على سبعة وعشرين قوسًا، أكبر جسر حجري من نوعه على الإطلاق.',
    // Pinned: the search matched "Magnia.jpg", a photo of Maghnia — a different
    // city four hundred kilometres away.
    commonsFile: 'File:Algerie Constantine Pont Sidi Rached.jpg',
    wiki: ['fr:Pont de Sidi Rached', 'en:Sidi Rached Bridge'],
    commonsCategory: 'Pont de Sidi Rached',
    commonsSearch: ['Pont Sidi Rached Constantine'],
  },
  {
    key: 'dz-cst-monument-aux-morts',
    city: 'Constantine', cat: 'viewpoint', lat: 36.3752, lng: 6.6137, min: 40, radius: 100,
    en: 'Monument aux Morts', fr: 'Monument aux Morts', ar: 'نصب الموتى',
    dEn: 'A replica Arch of Trajan on the cliff edge, with the whole gorge and the bridges below it.',
    dFr: "Réplique de l'arc de Trajan au bord de la falaise, avec toute la gorge et ses ponts en contrebas.",
    dAr: 'نسخة من قوس تراجان على حافة الجرف، تطل على الأخدود كاملًا وجسوره.',
    wiki: ['fr:Monument aux morts de Constantine'],
    commonsCategory: 'Monument aux morts (Constantine)',
    commonsSearch: ['Monument aux morts Constantine'],
  },
  {
    key: 'dz-cst-salah-bey',
    city: 'Constantine', cat: 'historical_monument', lat: 36.3565, lng: 6.6088, min: 30, radius: 150,
    en: 'Salah Bey Viaduct', fr: 'Viaduc Salah Bey', ar: 'جسر صالح باي',
    dEn: 'A cable-stayed bridge of 2014, 756 metres long, the modern counterpart to the city\'s stone crossings.',
    dFr: "Pont à haubans de 2014, long de 756 mètres, pendant contemporain des franchissements de pierre de la ville.",
    dAr: 'جسر بأسلاك مشدودة افتُتح عام 2014 بطول 756 مترًا، النظير الحديث لجسور المدينة الحجرية.',
    wiki: ['fr:Viaduc Salah Bey', 'en:Salah Bey Viaduct'],
    commonsCategory: 'Salah Bey Viaduct',
    commonsSearch: ['Salah Bey viaduct Constantine'],
  },
  {
    key: 'dz-cst-souk-el-ghezel',
    city: 'Constantine', cat: 'religious_site', lat: 36.364, lng: 6.614, min: 35, radius: 60,
    en: 'Souk El Ghezel Mosque', fr: 'Mosquée Souk El Ghezel', ar: 'جامع سوق الغزل',
    dEn: 'An Ottoman mosque of 1730 on the old wool market, briefly a cathedral, restored to prayer in 1962.',
    dFr: "Mosquée ottomane de 1730 sur l'ancien marché à la laine, brièvement cathédrale, rendue au culte en 1962.",
    dAr: 'جامع عثماني يعود لعام 1730 في سوق الصوف القديم، صار كاتدرائية لفترة ثم أُعيد للصلاة عام 1962.',
    wiki: ['fr:Mosquée Souk El Ghezel', 'en:Souk El Ghezel Mosque'],
    commonsCategory: 'Mosquée Souk El Ghezel',
    commonsSearch: ['Souk El Ghezel mosque Constantine'],
  },
  {
    key: 'dz-cst-sidi-el-kettani',
    city: 'Constantine', cat: 'religious_site', lat: 36.3665, lng: 6.61, min: 35, radius: 60,
    en: 'Sidi El Kettani Mosque', fr: 'Mosquée Sidi El Kettani', ar: 'جامع سيدي الكتاني',
    dEn: 'Built by Salah Bey in 1776 with a madrasa and hammam around it, in the heart of the old town.',
    dFr: "Élevée par Salah Bey en 1776 avec sa médersa et son hammam, au cœur de la vieille ville.",
    dAr: 'شيّده صالح باي عام 1776 ومعه مدرسة وحمّام، في قلب المدينة القديمة.',
    wiki: ['fr:Mosquée Sidi El Kettani', 'en:Sidi El Kettani Mosque'],
    commonsCategory: 'Mosquée Sidi El Kettani',
    commonsSearch: ['Kettani Constantine mosque', 'El-Kettani Constantine medersa'],
  },
  {
    key: 'dz-cst-tiddis',
    city: 'Constantine', cat: 'historical_monument', lat: 36.42, lng: 6.555, min: 90, radius: 250,
    en: 'Tiddis', fr: 'Tiddis', ar: 'تيديس',
    dEn: 'A Roman hill town of red rock thirty kilometres north-west, its stepped main street cut into the slope.',
    dFr: "Cité romaine de roche rouge à trente kilomètres au nord-ouest, sa rue principale taillée en escalier dans la pente.",
    dAr: 'مدينة رومانية من الصخر الأحمر على بعد ثلاثين كيلومترًا شمال غرب، شارعها الرئيسي محفور مدرجًا في المنحدر.',
    wiki: ['en:Tiddis', 'fr:Tiddis'],
    commonsCategory: 'Tiddis',
  },
  {
    key: 'dz-cst-massinissa',
    city: 'Constantine', cat: 'historical_monument', lat: 36.2617, lng: 6.6928, min: 45, radius: 120,
    en: 'Mausoleum of Massinissa', fr: 'Mausolée de Massinissa', ar: 'ضريح ماسينيسا',
    dEn: 'The stepped Numidian tower at El Khroub, held to be the tomb of the first king of a united Numidia.',
    dFr: "Tour numide à degrés du Khroub, tenue pour le tombeau du premier roi de la Numidie unifiée.",
    dAr: 'البرج النوميدي المدرج بالخروب، ويُعتقد أنه قبر أول ملوك نوميديا الموحدة.',
    wiki: ['fr:Mausolée de Massinissa', 'en:Mausoleum of Massinissa'],
    commonsCategory: 'Mausoleum of Massinissa',
    commonsSearch: ['Massinissa mausoleum El Khroub'],
  },
  // Place de la Brèche and the Malek Haddad Palace of Culture were both dropped
  // here rather than shipped. Neither has a usable photograph on Commons — the
  // cascade offered an 1837 engraving of the city being shelled for the square,
  // and a portrait of a French queen for the arts centre — and a POI with the
  // wrong picture is worse than one the catalogue does not claim to cover.
  // Restore them the moment a real photo exists.
  {
    key: 'dz-cst-theatre',
    city: 'Constantine', cat: 'cultural_venue', lat: 36.3648, lng: 6.6117, min: 40, radius: 60,
    en: 'Constantine Regional Theatre', fr: 'Théâtre Régional de Constantine', ar: 'المسرح الجهوي لقسنطينة',
    dEn: 'An Italianate theatre of 1883 on the Place de la Brèche, restored for the 2015 Capital of Arab Culture.',
    dFr: "Théâtre à l'italienne de 1883 sur la place de la Brèche, restauré pour la capitale de la culture arabe 2015.",
    dAr: 'مسرح على الطراز الإيطالي شُيد عام 1883 بساحة البريش، رُمم بمناسبة عاصمة الثقافة العربية 2015.',
    wiki: ['fr:Théâtre régional de Constantine'],
    commonsCategory: 'Théâtre régional de Constantine',
    commonsSearch: ['Théâtre régional Constantine'],
  },
  {
    key: 'dz-cst-djebel-ouahch',
    city: 'Constantine', cat: 'park_garden', lat: 36.4005, lng: 6.6644, min: 90, radius: 400,
    en: 'Djebel El Ouahch', fr: 'Djebel El Ouahch', ar: 'جبل الوحش',
    dEn: 'A pine forest park in the hills north-east of the city, with lakes and the local weekend picnic ground.',
    dFr: "Parc forestier de pins dans les collines au nord-est, avec ses lacs et les pique-niques du week-end.",
    dAr: 'حديقة غابية من الصنوبر في التلال شمال شرق المدينة، ببحيراتها ومتنزهات نهاية الأسبوع.',
    wiki: ['fr:Djebel El Ouahch'],
    commonsCategory: 'Djebel El Ouahch',
    commonsSearch: ['Djbel El Ouahch Constantine', 'Jbel Ouahch forest Constantine'],
  },
  {
    key: 'dz-cst-casbah',
    city: 'Constantine', cat: 'historical_monument', lat: 36.369, lng: 6.611, min: 60, radius: 200,
    en: 'Constantine Casbah', fr: 'Casbah de Constantine', ar: 'قصبة قسنطينة',
    dEn: 'The old quarter on the rock\'s northern tip, where Ottoman houses stop at the edge of the gorge.',
    dFr: "Le vieux quartier à la pointe nord du rocher, où les maisons ottomanes s'arrêtent au bord du gouffre.",
    dAr: 'الحي القديم في الطرف الشمالي للصخرة، حيث تنتهي البيوت العثمانية عند حافة الهاوية.',
    // Pinned: the only article for this quarter is the one about Constantine
    // itself, whose coordinates sit nine kilometres south of the casbah and
    // whose lead image is the Mellah Slimane footbridge — already a POI here.
    commonsFile: 'File:Constantine medina.jpg',
    commonsSearch: ['vieille ville Constantine maisons'],
  },
  {
    key: 'dz-cst-aqueduc',
    city: 'Constantine', cat: 'historical_monument', lat: 36.3502, lng: 6.6176, min: 35, radius: 100,
    en: 'Roman Aqueduct of Constantine', fr: 'Aqueduc romain de Constantine', ar: 'القناة الرومانية بقسنطينة',
    dEn: 'The surviving arches of the aqueduct that carried water to Roman Cirta across the Rhumel valley.',
    dFr: "Les arches subsistantes de l'aqueduc qui portait l'eau à la Cirta romaine par-dessus la vallée du Rhumel.",
    dAr: 'الأقواس المتبقية من القناة التي كانت تنقل المياه إلى سيرتا الرومانية عبر وادي الرمال.',
    wiki: ['fr:Aqueduc romain de Constantine'],
    commonsCategory: 'Roman aqueduct of Constantine',
    commonsSearch: ['Roman aqueduct Constantine Algeria', 'Aqueduc romain Constantine'],
  },
  {
    key: 'dz-cst-el-kantara',
    city: 'Constantine', cat: 'historical_monument', lat: 36.368, lng: 6.618, min: 30, radius: 90,
    en: 'El Kantara Bridge', fr: 'Pont El Kantara', ar: 'جسر القنطرة',
    dEn: 'The oldest crossing of the gorge, Roman in foundation and rebuilt in iron in 1863.',
    dFr: "Le plus ancien franchissement de la gorge, d'assise romaine et reconstruit en fer en 1863.",
    dAr: 'أقدم معابر الأخدود، أساسه روماني وأُعيد بناؤه بالحديد عام 1863.',
    wiki: ['fr:Pont d\'El Kantara', 'en:El Kantara Bridge'],
    commonsCategory: 'Pont El Kantara (Constantine)',
    commonsSearch: ['El Kantara bridge Constantine'],
  },
];
