-- Curated POI catalogue for the pilot cities, regenerated by
-- tool/poi_seed/resolve_images.mjs on 2026-08-15.
--
-- Every row carries a photo: the resolver drops any POI whose image could not be
-- fetched and verified, so "photo_url is not null" is an invariant of this file
-- rather than a property that happens to hold today. Coordinates are taken from
-- the subject's Wikipedia article where it has them.
--
-- Do not hand-edit. Change tool/poi_seed/catalogue.mjs and re-run the resolver.

begin;

-- Generated routes reference POIs by id, so they cannot outlive a catalogue
-- swap: a stop pointing at a deleted POI is a broken itinerary, and one
-- pointing at a *replacement* POI at the same id would be worse. Both go, and
-- with them the per-user progress and mascot spawns hung off those routes —
-- there is nothing left for them to be progress through.
--
-- Ordered by dependency, deepest first, because these are all NO ACTION FKs.
delete from public.progress;
delete from public.mascot_spawns;
delete from public.route_stops;
delete from public.routes;
delete from public.progress_events;
delete from public.pois;

insert into public.pois (
  city_id, category_id,
  name_en, name_fr, name_ar,
  description_en, description_fr, description_ar,
  location,
  opening_hours_raw, avg_visit_duration_minutes, checkpoint_radius_meters,
  external_ref,
  photo_url, photo_attribution, photo_license, photo_source_url
) values
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Casbah of Algiers', 'Casbah d''Alger', 'قصبة الجزائر',
    'A UNESCO-listed Ottoman citadel of stepped alleys, tiled courtyards and terraces falling towards the bay.', 'Citadelle ottomane classée à l''UNESCO : ruelles en escalier, patios carrelés et terrasses dévalant vers la baie.', 'قلعة عثمانية مصنفة ضمن التراث العالمي، بأزقتها المتدرجة وأفنيتها المبلطة وشرفاتها المطلة على الخليج.',
    st_setsrid(st_makepoint(3.06055556, 36.78694444), 4326)::geography,
    null, 120, 300,
    'dz-alg-casbah',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/AlgerCasbah.jpg/1280px-AlgerCasbah.jpg', 'toufik Lerari', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:AlgerCasbah.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Ketchaoua Mosque', 'Mosquée Ketchaoua', 'جامع كتشاوة',
    'The Casbah''s landmark mosque, built in 1612, made a cathedral under French rule and returned to worship in 1962.', 'Mosquée emblématique de la Casbah, bâtie en 1612, transformée en cathédrale sous la colonisation puis rendue au culte en 1962.', 'جامع القصبة الشهير، بُني عام 1612، حُوّل إلى كاتدرائية إبان الاستعمار ثم أُعيد للصلاة سنة 1962.',
    st_setsrid(st_makepoint(3.06055556, 36.785), 4326)::geography,
    null, 45, 80,
    'dz-alg-ketchaoua',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Ketchaoua_Mosque_-_Architectural_and_Cultural_Heritage_of_the_Casbah_of_Algiers_1.jpg/1280px-Ketchaoua_Mosque_-_Architectural_and_Cultural_Heritage_of_the_Casbah_of_Algiers_1.jpg', 'Rachid Hamatou', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ketchaoua_Mosque_-_Architectural_and_Cultural_Heritage_of_the_Casbah_of_Algiers_1.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Djamaa el Djazaïr', 'Grande Mosquée d''Alger', 'جامع الجزائر',
    'The third-largest mosque in the world, with a 265-metre minaret you can ride to the top of for the whole bay.', 'Troisième plus grande mosquée du monde, dont le minaret de 265 mètres s''ouvre sur toute la baie d''Alger.', 'ثالث أكبر مسجد في العالم، بمئذنة يبلغ ارتفاعها 265 مترًا تطل على خليج الجزائر بأكمله.',
    st_setsrid(st_makepoint(3.13805556, 36.73583333), 4326)::geography,
    null, 90, 250,
    'dz-alg-djamaa-el-djazair',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Djama%C3%A2_El_Djaza%C3%AFr_%E2%80%93_The_Great_Mosque_of_Algiers_11.jpg/1280px-Djama%C3%A2_El_Djaza%C3%AFr_%E2%80%93_The_Great_Mosque_of_Algiers_11.jpg', 'Rachid Hamatou', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Djama%C3%A2_El_Djaza%C3%AFr_%E2%80%93_The_Great_Mosque_of_Algiers_11.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Djamaa el Kebir', 'Grande Mosquée d''Alger (ancienne)', 'الجامع الكبير',
    'The oldest mosque still standing in Algiers, Almoravid in origin and barely changed since the eleventh century.', 'La plus ancienne mosquée d''Alger encore debout, d''origine almoravide et presque inchangée depuis le XIe siècle.', 'أقدم مسجد قائم في الجزائر العاصمة، مرابطي الأصل ولم يتغير تقريبًا منذ القرن الحادي عشر.',
    st_setsrid(st_makepoint(3.06416667, 36.78527778), 4326)::geography,
    null, 40, 70,
    'dz-alg-djamaa-el-kebir',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Alger_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9_%D8%A7%D9%84%D9%83%D8%A8%D9%8A%D8%B1_%D9%88_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9_%D8%A7%D9%84%D8%AC%D8%AF%D9%8A%D8%AF_%D8%A8%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1.jpg/1280px-Alger_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9_%D8%A7%D9%84%D9%83%D8%A8%D9%8A%D8%B1_%D9%88_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9_%D8%A7%D9%84%D8%AC%D8%AF%D9%8A%D8%AF_%D8%A8%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1.jpg', 'Habib kaki', 'CC0', 'https://commons.wikimedia.org/wiki/File:Alger_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9_%D8%A7%D9%84%D9%83%D8%A8%D9%8A%D8%B1_%D9%88_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9_%D8%A7%D9%84%D8%AC%D8%AF%D9%8A%D8%AF_%D8%A8%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Djamaa el Djedid', 'Mosquée de la Pêcherie', 'الجامع الجديد',
    'An Ottoman mosque of 1660 on the Place des Martyrs, its white dome the first thing seen from an arriving ship.', 'Mosquée ottomane de 1660 sur la place des Martyrs, dont la coupole blanche accueille les navires à l''arrivée.', 'مسجد عثماني يعود لعام 1660 في ساحة الشهداء، قبته البيضاء أول ما يراه القادم من البحر.',
    st_setsrid(st_makepoint(3.0608, 36.7838), 4326)::geography,
    null, 35, 70,
    'dz-alg-djamaa-el-djedid',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Alger-Place-des-Martyrs-Casbah_cropped.jpg/1280px-Alger-Place-des-Martyrs-Casbah_cropped.jpg', 'Ludovic Courtès', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Alger-Place-des-Martyrs-Casbah_cropped.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Notre-Dame d''Afrique', 'Basilique Notre-Dame d''Afrique', 'كنيسة السيدة الإفريقية',
    'A neo-Byzantine basilica on the cliff above Bologhine, facing the sea and inscribed "pray for us and for the Muslims".', 'Basilique néo-byzantine sur la falaise de Bologhine, tournée vers la mer et portant l''inscription « priez pour nous et pour les musulmans ».', 'كاتدرائية بالطراز البيزنطي الجديد على جرف بولوغين، تطل على البحر وتحمل عبارة «صلّوا لأجلنا ولأجل المسلمين».',
    st_setsrid(st_makepoint(3.0425, 36.80111111), 4326)::geography,
    null, 50, 120,
    'dz-alg-notre-dame-afrique',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Notre_Dame_d%27Afrique2_cropped.jpg/1280px-Notre_Dame_d%27Afrique2_cropped.jpg', 'Chettouh Nabil', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Notre_Dame_d%27Afrique2_cropped.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Maqam Echahid', 'Mémorial du Martyr', 'مقام الشهيد',
    'Three concrete palm fronds 92 metres high, raised in 1982 for the dead of the war of independence.', 'Trois palmes de béton de 92 mètres, érigées en 1982 à la mémoire des morts de la guerre d''indépendance.', 'ثلاث سعفات نخيل خرسانية بارتفاع 92 مترًا، شُيدت عام 1982 تخليدًا لشهداء حرب التحرير.',
    st_setsrid(st_makepoint(3.06972222, 36.74583333), 4326)::geography,
    null, 60, 150,
    'dz-alg-maqam-echahid',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Martyrs_Memorial._Algiers%2C_Algeria.jpg/1280px-Martyrs_Memorial._Algiers%2C_Algeria.jpg', 'Boumediene15', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Martyrs_Memorial._Algiers,_Algeria.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000003'::uuid,
    'Jardin d''Essai du Hamma', 'Jardin d''Essai du Hamma', 'حديقة التجارب بالحامة',
    'Thirty-two hectares of botanical garden laid out in 1832, with an avenue of dragon trees and a French formal parterre.', 'Trente-deux hectares de jardin botanique dessinés en 1832, avec son allée de dracaenas et son parterre à la française.', 'اثنان وثلاثون هكتارًا من الحدائق النباتية أُنشئت عام 1832، بممرها الشهير من أشجار التنين وحديقتها الفرنسية.',
    st_setsrid(st_makepoint(3.076, 36.748), 4326)::geography,
    'Tue–Sun 09:00–17:00', 120, 250,
    'dz-alg-jardin-essai',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/The_Test_Garden_Hamma.jpg/1280px-The_Test_Garden_Hamma.jpg', 'Khaled zouaoui', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:The_Test_Garden_Hamma.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'Bardo National Museum', 'Musée National du Bardo', 'متحف الباردو الوطني',
    'Prehistory and ethnography inside an eighteenth-century Ottoman villa, from Saharan rock art to Tuareg silver.', 'Préhistoire et ethnographie dans une villa ottomane du XVIIIe siècle, de l''art rupestre saharien à l''argent touareg.', 'ما قبل التاريخ والإثنوغرافيا داخل فيلا عثمانية من القرن الثامن عشر، من الفن الصخري الصحراوي إلى فضة الطوارق.',
    st_setsrid(st_makepoint(3.04638889, 36.76027778), 4326)::geography,
    'Sun–Thu 09:00–16:30', 75, 80,
    'dz-alg-bardo',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Diwan%2C_Bardo_d%27Alger_4.jpg/1280px-Diwan%2C_Bardo_d%27Alger_4.jpg', 'Reda Kerbush', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Diwan,_Bardo_d%27Alger_4.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'National Museum of Fine Arts', 'Musée National des Beaux-Arts', 'المتحف الوطني للفنون الجميلة',
    'Africa''s largest fine-art collection, eight thousand works stacked over five floors above the Jardin d''Essai.', 'La plus grande collection d''art d''Afrique : huit mille œuvres sur cinq niveaux, au-dessus du Jardin d''Essai.', 'أكبر مجموعة فنية في إفريقيا، ثمانية آلاف عمل موزعة على خمسة طوابق فوق حديقة التجارب.',
    st_setsrid(st_makepoint(3.0723, 36.7461), 4326)::geography,
    'Sun–Thu 10:00–17:00', 90, 80,
    'dz-alg-beaux-arts',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/National_Museum_of_Fine_Arts_of_Algiers_01.jpg/1280px-National_Museum_of_Fine_Arts_of_Algiers_01.jpg', 'Dezedien', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:National_Museum_of_Fine_Arts_of_Algiers_01.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'MAMA — Museum of Modern Art', 'Musée d''Art Moderne d''Alger', 'متحف الجزائر للفن الحديث',
    'Contemporary Algerian and African art in a Neo-Moorish former department store on rue Larbi Ben M''hidi.', 'Art algérien et africain contemporain dans un ancien grand magasin néo-mauresque de la rue Larbi Ben M''hidi.', 'فن جزائري وإفريقي معاصر داخل متجر كبير سابق بالطراز المغاربي الجديد في شارع العربي بن مهيدي.',
    st_setsrid(st_makepoint(3.05, 36.7667), 4326)::geography,
    'Sat–Thu 10:00–18:00', 60, 60,
    'dz-alg-mama',
    'https://upload.wikimedia.org/wikipedia/commons/b/b5/Mus%C3%A9e_d%27art_moderne_d%27Alger.jpg', 'Rvince', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_d%27art_moderne_d%27Alger.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Bastion 23 — Palais des Raïs', 'Bastion 23 — Palais des Raïs', 'قصر الرياس - الحصن 23',
    'Three Ottoman corsair palaces and a fisherman''s house, the last surviving piece of the lower Casbah''s sea front.', 'Trois palais de raïs ottomans et une maison de pêcheurs, dernier fragment du front de mer de la basse Casbah.', 'ثلاثة قصور لرياس عثمانيين وبيت صياد، آخر ما تبقّى من الواجهة البحرية للقصبة السفلى.',
    st_setsrid(st_makepoint(3.06398, 36.788434), 4326)::geography,
    null, 60, 100,
    'dz-alg-bastion-23',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Palais_des_Rais_%28Es%27hine%29_-_Alger.JPG/1280px-Palais_des_Rais_%28Es%27hine%29_-_Alger.JPG', 'Mimosa dz', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Palais_des_Rais_(Es%27hine)_-_Alger.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'National Museum of Antiquities', 'Musée National des Antiquités', 'المتحف الوطني للآثار',
    'Roman mosaics, Punic steles and Islamic metalwork in Algeria''s oldest museum, founded in 1838.', 'Mosaïques romaines, stèles puniques et dinanderie islamique dans le plus ancien musée d''Algérie, fondé en 1838.', 'فسيفساء رومانية وأنصاب بونيقية ومشغولات إسلامية في أقدم متاحف الجزائر، تأسس عام 1838.',
    st_setsrid(st_makepoint(3.0458834, 36.7624602), 4326)::geography,
    'Sun–Thu 09:00–16:00', 70, 70,
    'dz-alg-antiquites',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Mus%C3%A9e_national_des_antiquit%C3%A9s_et_des_arts_islamiques%2C_Alger.jpg/1280px-Mus%C3%A9e_national_des_antiquit%C3%A9s_et_des_arts_islamiques%2C_Alger.jpg', 'Riad Salih', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_national_des_antiquit%C3%A9s_et_des_arts_islamiques,_Alger.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000006'::uuid,
    'Algerian National Theatre', 'Théâtre National Algérien', 'المسرح الوطني الجزائري',
    'An 1853 Italianate opera house on Place Port Saïd, still the country''s principal stage.', 'Salle à l''italienne de 1853 sur la place Port-Saïd, toujours la première scène du pays.', 'مسرح على الطراز الإيطالي شُيد عام 1853 بساحة بور سعيد، ولا يزال أهم خشبة في البلاد.',
    st_setsrid(st_makepoint(3.06, 36.7813), 4326)::geography,
    null, 45, 60,
    'dz-alg-tna',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/1229._-ALGER._-_Le_Th%C3%A9%C3%A2tre_Municipal_et_Place_de_la_R%C3%A9publique_-_E._S.jpg/1280px-1229._-ALGER._-_Le_Th%C3%A9%C3%A2tre_Municipal_et_Place_de_la_R%C3%A9publique_-_E._S.jpg', 'Unknown author Unknown author', 'Public domain', 'https://commons.wikimedia.org/wiki/File:1229._-ALGER._-_Le_Th%C3%A9%C3%A2tre_Municipal_et_Place_de_la_R%C3%A9publique_-_E._S.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Grande Poste d''Alger', 'Grande Poste d''Alger', 'البريد المركزي بالجزائر',
    'The 1910 central post office, the high point of Neo-Moorish architecture and the city''s default meeting spot.', 'La poste centrale de 1910, sommet du style néo-mauresque et point de rendez-vous par défaut des Algérois.', 'مبنى البريد المركزي المشيد عام 1910، ذروة الطراز المغاربي الجديد ومكان اللقاء المعتاد لسكان العاصمة.',
    st_setsrid(st_makepoint(3.059435, 36.773096), 4326)::geography,
    null, 30, 80,
    'dz-alg-grande-poste',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/La_Grande_Poste_d%27Alger.jpg/1280px-La_Grande_Poste_d%27Alger.jpg', 'Chettouh Nabil', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:La_Grande_Poste_d%27Alger.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Place des Martyrs', 'Place des Martyrs', 'ساحة الشهداء',
    'The square at the foot of the Casbah, with an Ottoman and Roman excavation displayed inside the metro station below.', 'La place au pied de la Casbah, dont les fouilles ottomanes et romaines sont exposées dans la station de métro en dessous.', 'الساحة الواقعة أسفل القصبة، وتُعرض حفرياتها العثمانية والرومانية داخل محطة المترو تحتها.',
    st_setsrid(st_makepoint(3.0625, 36.7847), 4326)::geography,
    null, 30, 120,
    'dz-alg-place-martyrs',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Place_des_martyrs_Alger_Alg%C3%A9rie.jpg/1280px-Place_des_martyrs_Alger_Alg%C3%A9rie.jpg', 'Salaheddine Gharib', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Place_des_martyrs_Alger_Alg%C3%A9rie.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Citadel of Algiers', 'Citadelle d''Alger', 'قلعة الجزائر',
    'The Dey''s fortress crowning the Casbah, where the fan-blow of 1827 gave France its pretext for invasion.', 'La forteresse du Dey au sommet de la Casbah, où le coup d''éventail de 1827 offrit à la France son prétexte.', 'قلعة الداي في أعلى القصبة، حيث وقعت حادثة المروحة عام 1827 التي اتخذتها فرنسا ذريعة للغزو.',
    st_setsrid(st_makepoint(3.0588, 36.7842), 4326)::geography,
    null, 60, 120,
    'dz-alg-citadelle',
    'https://upload.wikimedia.org/wikipedia/commons/8/81/Dar_Soltan_Alger.jpg', 'Yves Jalabert from La Rochelle, France', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Dar_Soltan_Alger.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Dar Hassan Pacha', 'Dar Hassan Pacha', 'دار حسن باشا',
    'A 1791 Ottoman palace of galleried courtyards, later the winter residence of the French governors-general.', 'Palais ottoman de 1791 aux patios à galeries, devenu résidence d''hiver des gouverneurs généraux français.', 'قصر عثماني يعود لعام 1791 بأفنيته ذات الأروقة، صار لاحقًا المقر الشتوي للحكام العامين الفرنسيين.',
    st_setsrid(st_makepoint(3.061544, 36.785045), 4326)::geography,
    null, 40, 60,
    'dz-alg-dar-hassan-pacha',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Balustrade._Interieur_du_palais_Hassan_Pacha_-_Alger_-_Alg%C3%A9rie.JPG/1280px-Balustrade._Interieur_du_palais_Hassan_Pacha_-_Alger_-_Alg%C3%A9rie.JPG', 'Aziza Ines', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Balustrade._Interieur_du_palais_Hassan_Pacha_-_Alger_-_Alg%C3%A9rie.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Dar Aziza', 'Dar Aziza', 'دار عزيزة',
    'A sixteenth-century palace beside Ketchaoua, its arcaded patio the textbook example of Algerine domestic architecture.', 'Palais du XVIe siècle voisin de Ketchaoua, dont le patio à arcades est l''exemple canonique de la maison algéroise.', 'قصر من القرن السادس عشر بجوار جامع كتشاوة، فناؤه المقنطر نموذج مرجعي للعمارة السكنية الجزائرية.',
    st_setsrid(st_makepoint(3.061544, 36.785045), 4326)::geography,
    null, 35, 60,
    'dz-alg-dar-aziza',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Patio_de_Dar_Aziza.jpg/1280px-Patio_de_Dar_Aziza.jpg', 'InesNines', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Patio_de_Dar_Aziza.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Sidi Abderrahmane Mosque', 'Mosquée Sidi Abderrahmane', 'جامع سيدي عبد الرحمن',
    'The mausoleum-mosque of the city''s patron saint, set in a walled garden of cypresses inside the upper Casbah.', 'Mosquée-mausolée du saint patron de la ville, dans un jardin clos de cyprès au cœur de la haute Casbah.', 'مسجد وضريح شفيع المدينة، وسط حديقة مسوّرة من أشجار السرو في أعالي القصبة.',
    st_setsrid(st_makepoint(3.06417, 36.78528), 4326)::geography,
    null, 35, 60,
    'dz-alg-sidi-abderrahmane',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Mosqu%C3%A9e_de_Sidi_Abderrahmane%2C_Alger_c.1858.jpg/1280px-Mosqu%C3%A9e_de_Sidi_Abderrahmane%2C_Alger_c.1858.jpg', 'Félix-Jacques Moulin', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Mosqu%C3%A9e_de_Sidi_Abderrahmane,_Alger_c.1858.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'Museum of Popular Arts and Traditions', 'Musée des Arts et Traditions Populaires', 'متحف الفنون والتقاليد الشعبية',
    'Costume, jewellery and woodwork in Dar Khedaoudj el Amia, a merchant''s house of 1570 in the heart of the Casbah.', 'Costumes, bijoux et boiseries dans Dar Khedaoudj el Amia, maison de marchand de 1570 au cœur de la Casbah.', 'أزياء وحلي وأشغال خشبية في دار خديجة العمياء، بيت تاجر يعود لعام 1570 في قلب القصبة.',
    st_setsrid(st_makepoint(3.060963, 36.786724), 4326)::geography,
    'Sun–Thu 09:00–16:00', 50, 50,
    'dz-alg-arts-traditions',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Palace_khdaouedj_amia.jpg/1280px-Palace_khdaouedj_amia.jpg', 'Abderrahmane boudjenane', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Palace_khdaouedj_amia.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000006'::uuid,
    'Villa Abd-el-Tif', 'Villa Abd-el-Tif', 'فيلا عبد اللطيف',
    'An Ottoman country house above the Jardin d''Essai that housed a residency for French painters from 1907.', 'Maison de campagne ottomane dominant le Jardin d''Essai, résidence de peintres français à partir de 1907.', 'منزل ريفي عثماني يعلو حديقة التجارب، احتضن إقامة فنية للرسامين الفرنسيين منذ عام 1907.',
    st_setsrid(st_makepoint(3.0733039, 36.7450387), 4326)::geography,
    null, 45, 70,
    'dz-alg-villa-abdeltif',
    'https://upload.wikimedia.org/wikipedia/commons/e/e3/Dar_Abdel-Latif%2C_Alger%2CAlgeria_04.jpg', 'Till Vallee', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Dar_Abdel-Latif,_Alger,Algeria_04.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000006'::uuid,
    'Riadh El Feth', 'Riadh El Feth', 'رياض الفتح',
    'The terraced arts and shopping complex under the Martyrs'' Memorial, with galleries and a terrace over the bay.', 'Complexe culturel et commercial en terrasses sous le Mémorial du Martyr, avec galeries et vue sur la baie.', 'مركب ثقافي وتجاري مدرج أسفل مقام الشهيد، يضم أروقة فنية وشرفة تطل على الخليج.',
    st_setsrid(st_makepoint(3.070135, 36.742908), 4326)::geography,
    null, 75, 120,
    'dz-alg-riadh-el-feth',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Oref_monument.jpg/1280px-Oref_monument.jpg', 'Sam filar', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Oref_monument.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'National Museum of the Mujahid', 'Musée National du Moudjahid', 'المتحف الوطني للمجاهد',
    'The war of independence told through weapons, photographs and prison letters, beneath the Martyrs'' Memorial.', 'La guerre d''indépendance racontée par les armes, les photographies et les lettres de prison, sous le Mémorial du Martyr.', 'حرب التحرير مروية عبر الأسلحة والصور ورسائل السجون، أسفل مقام الشهيد.',
    st_setsrid(st_makepoint(3.07, 36.7452), 4326)::geography,
    'Sat–Thu 09:00–17:00', 60, 70,
    'dz-alg-moudjahid',
    'https://upload.wikimedia.org/wikipedia/commons/f/f2/Mus%C3%A9e_national_du_moudjahid_1.jpg', 'Kingdz16', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_national_du_moudjahid_1.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000003'::uuid,
    'Prague Garden', 'Jardin de Prague', 'حديقة براغ',
    'A terraced garden above Bab El Oued, formerly Marengo, looking down on Notre-Dame d''Afrique.', 'Jardin en terrasses au-dessus de Bab El Oued, ancien Marengo, dominant Notre-Dame d''Afrique.', 'حديقة مدرجة فوق باب الوادي، كانت تُسمى مارينغو، تطل على كنيسة السيدة الإفريقية.',
    st_setsrid(st_makepoint(3.0590285, 36.7890322), 4326)::geography,
    null, 30, 90,
    'dz-alg-jardin-prague',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Prague_garden_%28Ex._marengo%29_Algiers_04.jpg/1280px-Prague_garden_%28Ex._marengo%29_Algiers_04.jpg', 'MohAdm', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Prague_garden_(Ex._marengo)_Algiers_04.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000007'::uuid,
    'Les Sablettes', 'Plage des Sablettes', 'شاطئ السابلات',
    'A reclaimed two-kilometre seafront promenade and beach east of the port, busiest at sunset.', 'Deux kilomètres de promenade et de plage gagnés sur la mer à l''est du port, animés au coucher du soleil.', 'كيلومتران من الممشى والشاطئ المستصلحين شرق الميناء، يزدحمان عند الغروب.',
    st_setsrid(st_makepoint(3.1174, 36.744), 4326)::geography,
    null, 90, 300,
    'dz-alg-sablettes',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Plage_des_Sablettes_%C3%A0_Alger.JPG/1280px-Plage_des_Sablettes_%C3%A0_Alger.JPG', 'Yelles', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Plage_des_Sablettes_%C3%A0_Alger.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000010'::uuid, '00000000-0000-4000-b000-000000000007'::uuid,
    'Palm Beach, Staoueli', 'Palm Beach (Staoueli)', 'شاطئ النخيل بسطاوالي',
    'A pine-backed sand beach on the western corniche, the calmest of the capital''s swimming beaches.', 'Plage de sable adossée aux pins sur la corniche ouest, la plus calme des plages de baignade de la capitale.', 'شاطئ رملي تحيط به أشجار الصنوبر على الكورنيش الغربي، أهدأ شواطئ العاصمة للسباحة.',
    st_setsrid(st_makepoint(2.8797, 36.7561), 4326)::geography,
    null, 90, 250,
    'dz-alg-palm-beach',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Palm_Beach_%D8%B4%D8%A7%D8%B7%D8%A6_%D8%A7%D9%84%D9%86%D8%AE%D9%8A%D9%84_-_panoramio.jpg/1280px-Palm_Beach_%D8%B4%D8%A7%D8%B7%D8%A6_%D8%A7%D9%84%D9%86%D8%AE%D9%8A%D9%84_-_panoramio.jpg', 'habib kaki', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Palm_Beach_%D8%B4%D8%A7%D8%B7%D8%A6_%D8%A7%D9%84%D9%86%D8%AE%D9%8A%D9%84_-_panoramio.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Fort Santa Cruz', 'Fort de Santa Cruz', 'حصن سانتا كروز',
    'A Spanish fortress of 1577 on the shoulder of Murdjadjo, four hundred metres straight above the harbour.', 'Forteresse espagnole de 1577 accrochée au Murdjadjo, à quatre cents mètres à l''aplomb du port.', 'حصن إسباني يعود لعام 1577 على سفح جبل مرجاجو، على ارتفاع أربعمائة متر فوق الميناء.',
    st_setsrid(st_makepoint(-0.665, 35.7092), 4326)::geography,
    null, 75, 150,
    'dz-orn-santa-cruz',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Oran_Santa_Cruz.JPG/1280px-Oran_Santa_Cruz.JPG', 'Photographer and original uploader was Mecifi at fr.wikipedia', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Oran_Santa_Cruz.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Chapel of Santa Cruz', 'Chapelle de Santa Cruz', 'كنيسة سانتا كروز',
    'A votive chapel raised in 1849 after the cholera lifted, on the ridge below the fort.', 'Chapelle votive élevée en 1849 après la fin du choléra, sur la crête au-dessous du fort.', 'كنيسة نذرية شُيدت عام 1849 بعد انحسار وباء الكوليرا، على الحافة أسفل الحصن.',
    st_setsrid(st_makepoint(-0.6555, 35.7055), 4326)::geography,
    null, 40, 100,
    'dz-orn-chapelle-santa-cruz',
    'https://upload.wikimedia.org/wikipedia/commons/5/56/Oran_Santa_Cruz_bis.JPG', 'Mecifi', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Oran_Santa_Cruz_bis.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000005'::uuid,
    'Murdjadjo', 'Murdjadjo', 'جبل مرجاجو',
    'The mountain that shelters Oran, with the whole gulf and Mers el-Kébir laid out from the crest road.', 'La montagne qui abrite Oran : depuis la route de crête, tout le golfe et Mers el-Kébir s''étalent.', 'الجبل الذي يحتضن وهران، ومن طريق قمته يمتد الخليج بأكمله والمرسى الكبير.',
    st_setsrid(st_makepoint(-0.6674, 35.7089), 4326)::geography,
    null, 60, 400,
    'dz-orn-murdjadjo',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Oran_vu_depuis_le_Murdjadjo_1930.JPG/1280px-Oran_vu_depuis_le_Murdjadjo_1930.JPG', 'Tmouchentois', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Oran_vu_depuis_le_Murdjadjo_1930.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Palace of the Bey', 'Palais du Bey', 'قصر الباي',
    'The residence built for Bey Mohamed el-Kebir after he took Oran back from Spain in 1792.', 'La résidence bâtie pour le bey Mohamed el-Kébir après la reprise d''Oran aux Espagnols en 1792.', 'المقر الذي بُني للباي محمد الكبير بعد استرجاعه وهران من الإسبان عام 1792.',
    st_setsrid(st_makepoint(-0.6493, 35.7057), 4326)::geography,
    null, 60, 90,
    'dz-orn-palais-bey',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/The_Bey%E2%80%99s_Palace_of_Oran_6.jpg/1280px-The_Bey%E2%80%99s_Palace_of_Oran_6.jpg', 'Rachid Hamatou', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:The_Bey%E2%80%99s_Palace_of_Oran_6.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Pasha Mosque', 'Mosquée du Pacha', 'مسجد الباشا',
    'Oran''s oldest working mosque, paid for in 1796 out of the ransom of Spanish prisoners.', 'La plus ancienne mosquée en activité d''Oran, financée en 1796 par la rançon des prisonniers espagnols.', 'أقدم مسجد عامل في وهران، مُوّل عام 1796 من فدية الأسرى الإسبان.',
    st_setsrid(st_makepoint(-0.650079, 35.705197), 4326)::geography,
    null, 35, 60,
    'dz-orn-mosquee-pacha',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/IMG_mosqu%C3%A9e.jpg/1280px-IMG_mosqu%C3%A9e.jpg', 'Oxbow3131', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:IMG_mosqu%C3%A9e.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Abdellah Ben Salem Mosque', 'Mosquée Abdellah Ben Salem', 'مسجد عبد الله بن سالم',
    'Built in 1880 as the Great Synagogue of Oran, one of North Africa''s largest, and a mosque since 1975.', 'Édifiée en 1880 comme grande synagogue d''Oran, l''une des plus vastes d''Afrique du Nord, mosquée depuis 1975.', 'شُيد عام 1880 ككنيس وهران الكبير، أحد أكبر كنس شمال إفريقيا، وتحوّل مسجدًا منذ 1975.',
    st_setsrid(st_makepoint(-0.65027778, 35.7), 4326)::geography,
    null, 35, 60,
    'dz-orn-ben-salem',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Mosqu%C3%A9e_Abdallah_Ibn_Salam_%28ancienne_Synagogue_d%27Oran%29_en_2011.JPG/1280px-Mosqu%C3%A9e_Abdallah_Ibn_Salam_%28ancienne_Synagogue_d%27Oran%29_en_2011.JPG', 'DZ-WahranUser', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Mosqu%C3%A9e_Abdallah_Ibn_Salam_(ancienne_Synagogue_d%27Oran)_en_2011.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'Ahmed Zabana National Museum', 'Musée National Ahmed Zabana', 'متحف أحمد زبانة الوطني',
    'Oran''s general museum since 1935: prehistory, Roman finds, natural history and a fine-art wing.', 'Le musée généraliste d''Oran depuis 1935 : préhistoire, antiquités romaines, histoire naturelle et beaux-arts.', 'المتحف العام لوهران منذ 1935: ما قبل التاريخ، آثار رومانية، تاريخ طبيعي وجناح للفنون الجميلة.',
    st_setsrid(st_makepoint(-0.64527778, 35.69583333), 4326)::geography,
    'Sat–Thu 09:00–16:30', 75, 70,
    'dz-orn-zabana',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Mus%C3%A9e_national_d%27Oran.jpg/1280px-Mus%C3%A9e_national_d%27Oran.jpg', 'Maya-Anaïs Yataghène', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_national_d%27Oran.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000006'::uuid,
    'Oran Regional Theatre', 'Théâtre Régional d''Oran', 'المسرح الجهوي لوهران',
    'A 1907 municipal theatre on Place du 1er Novembre, named for the playwright Abdelkader Alloula.', 'Théâtre municipal de 1907 sur la place du 1er-Novembre, baptisé du nom du dramaturge Abdelkader Alloula.', 'مسرح بلدي شُيد عام 1907 بساحة أول نوفمبر، يحمل اسم الكاتب المسرحي عبد القادر علولة.',
    st_setsrid(st_makepoint(-0.6365, 35.6975), 4326)::geography,
    null, 45, 60,
    'dz-orn-theatre',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Th%C3%A9%C3%A2tre_oran.jpg/1280px-Th%C3%A9%C3%A2tre_oran.jpg', 'Oxbow3131', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Th%C3%A9%C3%A2tre_oran.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Place du 1er Novembre', 'Place du 1er Novembre 1954', 'ساحة أول نوفمبر 1954',
    'The city''s central square, ringed by the theatre and town hall around an 1898 marble obelisk.', 'La place centrale, cernée par le théâtre et l''hôtel de ville autour d''un obélisque de marbre de 1898.', 'الساحة المركزية للمدينة، يحيط بها المسرح والبلدية حول مسلة رخامية تعود لعام 1898.',
    st_setsrid(st_makepoint(-0.6355, 35.6968), 4326)::geography,
    null, 30, 100,
    'dz-orn-place-1er-novembre',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Place_d%27armes.jpg/1280px-Place_d%27armes.jpg', 'Boumlik Messaïli', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Place_d%27armes.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000006'::uuid,
    'Sacred Heart Cathedral', 'Cathédrale du Sacré-Cœur', 'كاتدرائية القلب المقدس',
    'A vast Neo-Byzantine cathedral of 1913, deconsecrated in 1984 and now the city''s public library.', 'Immense cathédrale néo-byzantine de 1913, désaffectée en 1984 et devenue la bibliothèque municipale.', 'كاتدرائية ضخمة بالطراز البيزنطي الجديد شُيدت عام 1913، أُغلقت عام 1984 وصارت المكتبة البلدية.',
    st_setsrid(st_makepoint(-0.646321, 35.700235), 4326)::geography,
    null, 40, 60,
    'dz-orn-cathedrale',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cath%C3%A9drale_du_Sacr%C3%A9-C%C5%93ur_d%27Oran_01.jpg/1280px-Cath%C3%A9drale_du_Sacr%C3%A9-C%C5%93ur_d%27Oran_01.jpg', 'Bernard Gagnon', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Cath%C3%A9drale_du_Sacr%C3%A9-C%C5%93ur_d%27Oran_01.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Château Neuf', 'Château Neuf', 'القصر الجديد',
    'The Spanish citadel of 1563 above Sidi El Houari, later the seat of the beys and of French command.', 'Citadelle espagnole de 1563 dominant Sidi El Houari, plus tard siège des beys puis du commandement français.', 'قلعة إسبانية تعود لعام 1563 تعلو سيدي الهواري، صارت لاحقًا مقرًا للبايات ثم للقيادة الفرنسية.',
    st_setsrid(st_makepoint(-0.644, 35.701), 4326)::geography,
    null, 45, 100,
    'dz-orn-chateau-neuf',
    'https://upload.wikimedia.org/wikipedia/commons/0/02/Chateau_neuf_Oran_Algerie.jpg', 'ALIOUANE Kheira 31', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Chateau_neuf_Oran_Algerie.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Fort Lamoune', 'Fort Lamoune', 'حصن لامون',
    'A sea-level Spanish bastion guarding the western approach to the old harbour.', 'Bastion espagnol au ras de l''eau, gardant l''accès occidental au vieux port.', 'حصن إسباني على مستوى البحر يحرس المدخل الغربي للميناء القديم.',
    st_setsrid(st_makepoint(-0.6565, 35.7136), 4326)::geography,
    null, 40, 90,
    'dz-orn-fort-lamoune',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Alg%C3%A9rie_-_Oranie_-_49.jpg/1280px-Alg%C3%A9rie_-_Oranie_-_49.jpg', 'Maya-Anaïs Yataghène from Paris, France', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Alg%C3%A9rie_-_Oranie_-_49.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Mers el-Kébir', 'Mers el-Kébir', 'المرسى الكبير',
    'The great natural harbour west of Oran, fortified since antiquity and known for the naval action of 1940.', 'Le grand port naturel à l''ouest d''Oran, fortifié depuis l''Antiquité et connu pour l''affaire navale de 1940.', 'الميناء الطبيعي الكبير غرب وهران، محصّن منذ العصور القديمة ومعروف بمعركته البحرية عام 1940.',
    st_setsrid(st_makepoint(-0.6994, 35.7376), 4326)::geography,
    null, 60, 250,
    'dz-orn-mers-el-kebir',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Mers_El_K%C3%A9bir_%E2%80%93_Strategic_Naval_Port_and_Historic_Site_on_the_Algerian_Coast_1.jpg/1280px-Mers_El_K%C3%A9bir_%E2%80%93_Strategic_Naval_Port_and_Historic_Site_on_the_Algerian_Coast_1.jpg', 'Rachid Hamatou', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Mers_El_K%C3%A9bir_%E2%80%93_Strategic_Naval_Port_and_Historic_Site_on_the_Algerian_Coast_1.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000007'::uuid,
    'Les Andalouses', 'Les Andalouses', 'شاطئ الأندلسيات',
    'A long sand beach twenty-five kilometres west of the city, sheltered under the Murdjadjo foothills.', 'Longue plage de sable à vingt-cinq kilomètres à l''ouest, abritée au pied du Murdjadjo.', 'شاطئ رملي طويل على بعد خمسة وعشرين كيلومترًا غرب المدينة، في حماية سفوح مرجاجو.',
    st_setsrid(st_makepoint(-0.8281, 35.7597), 4326)::geography,
    null, 120, 350,
    'dz-orn-andalouses',
    'https://upload.wikimedia.org/wikipedia/commons/e/e0/LES_ANDALOUSES_BAY-ORAN.jpg', 'Ppm90sd', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:LES_ANDALOUSES_BAY-ORAN.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000007'::uuid,
    'Aïn El Turk', 'Aïn El Turk', 'عين الترك',
    'The seaside town on the corniche west of Oran, and the busiest stretch of coast in the wilaya.', 'La station balnéaire de la corniche à l''ouest d''Oran, portion de côte la plus fréquentée de la wilaya.', 'مدينة ساحلية على الكورنيش غرب وهران، وأكثر شواطئ الولاية ازدحامًا.',
    st_setsrid(st_makepoint(-0.74916667, 35.74083333), 4326)::geography,
    null, 100, 350,
    'dz-orn-ain-el-turk',
    'https://upload.wikimedia.org/wikipedia/commons/6/64/Ain_turck%2C_Oran_Province_%28Algeria%29.JPG', 'Imad007 at English Wikipedia', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Ain_turck,_Oran_Province_(Algeria).JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000003'::uuid,
    'Promenade de Létang', 'Promenade de Létang', 'ممشى ليتانغ',
    'The balcony boulevard above the port, laid out in the 1840s and still Oran''s evening walk.', 'Le boulevard-balcon au-dessus du port, tracé dans les années 1840 et toujours la promenade du soir.', 'الجادة المطلة على الميناء، شُقّت في أربعينيات القرن التاسع عشر ولا تزال ممشى المساء في وهران.',
    st_setsrid(st_makepoint(-0.629, 35.699), 4326)::geography,
    null, 45, 200,
    'dz-orn-front-de-mer',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Bild_fr%C3%A5n_familjen_von_Hallwyls_resa_genom_Algeriet_och_Tunisien%2C_1889-1890_-_Hallwylska_museet_-_92026.tif/lossy-page1-1280px-Bild_fr%C3%A5n_familjen_von_Hallwyls_resa_genom_Algeriet_och_Tunisien%2C_1889-1890_-_Hallwylska_museet_-_92026.tif.jpg', 'Unknown author Unknown author', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Bild_fr%C3%A5n_familjen_von_Hallwyls_resa_genom_Algeriet_och_Tunisien,_1889-1890_-_Hallwylska_museet_-_92026.tif'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Medina Jdida', 'Medina Jdida', 'المدينة الجديدة',
    'The "new town" of 1845, built for Oran''s Muslim population and still the city''s trading quarter.', 'La « ville nouvelle » de 1845, bâtie pour la population musulmane d''Oran et toujours son quartier commerçant.', '«المدينة الجديدة» المشيدة عام 1845 لسكان وهران المسلمين، ولا تزال حيّها التجاري.',
    st_setsrid(st_makepoint(-0.6473, 35.6955), 4326)::geography,
    null, 60, 250,
    'dz-orn-medina-jdida',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Tahtaha.jpg/1280px-Tahtaha.jpg', 'Boumlik Messaïli', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Tahtaha.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Sidi El Houari', 'Sidi El Houari', 'سيدي الهواري',
    'Oran''s founding quarter beneath the Château Neuf, with Ottoman baths, the Pasha mosque and Spanish walls.', 'Le quartier fondateur d''Oran sous le Château-Neuf : bains ottomans, mosquée du Pacha et murailles espagnoles.', 'الحي المؤسس لوهران أسفل القصر الجديد، بحماماته العثمانية ومسجد الباشا وأسواره الإسبانية.',
    st_setsrid(st_makepoint(-0.6488, 35.7013), 4326)::geography,
    null, 75, 250,
    'dz-orn-sidi-el-houari',
    'https://upload.wikimedia.org/wikipedia/commons/f/f9/%D9%85%D8%B3%D8%AC%D8%AF_%D8%A7%D9%84%D8%A7%D9%85%D8%A7%D9%85_%D8%A7%D9%84%D9%87%D9%88%D8%A7%D8%B1%D9%8A.jpg', 'Saidi31000', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:%D9%85%D8%B3%D8%AC%D8%AF_%D8%A7%D9%84%D8%A7%D9%85%D8%A7%D9%85_%D8%A7%D9%84%D9%87%D9%88%D8%A7%D8%B1%D9%8A.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000005'::uuid,
    'Djebel Santon', 'Djebel Santon', 'جبل سانتون',
    'A hilltop fort over Mers el-Kébir, the best single view of the bay and the naval base below.', 'Fort de sommet dominant Mers el-Kébir, la plus belle vue d''ensemble sur la baie et la base navale.', 'حصن على قمة تطل على المرسى الكبير، وأجمل إطلالة على الخليج والقاعدة البحرية أسفله.',
    st_setsrid(st_makepoint(-0.7119, 35.7347), 4326)::geography,
    null, 45, 150,
    'dz-orn-santon',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Djebel_Santon_Oran_%281%29.jpg/1280px-Djebel_Santon_Oran_%281%29.jpg', 'Bachounda', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Djebel_Santon_Oran_(1).jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000020'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Gambetta', 'Gambetta', 'قمبيطة',
    'A colonial-era district of wide avenues and 1930s facades on the eastern plateau above the port.', 'Quartier colonial aux larges avenues et façades des années 1930, sur le plateau est au-dessus du port.', 'حي من الحقبة الاستعمارية بجاداته الواسعة وواجهاته من الثلاثينيات، على الهضبة الشرقية فوق الميناء.',
    st_setsrid(st_makepoint(-0.6215, 35.7069), 4326)::geography,
    null, 30, 120,
    'dz-orn-gambetta',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Gambetta_rond_point_Oran_Alg%C3%A9rie.jpg/1280px-Gambetta_rond_point_Oran_Alg%C3%A9rie.jpg', 'Bachounda', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Gambetta_rond_point_Oran_Alg%C3%A9rie.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Sidi M''Cid Bridge', 'Pont de Sidi M''Cid', 'جسر سيدي مسيد',
    'A suspension bridge of 1912 slung 175 metres above the Rhumel — the highest in the world when it opened.', 'Pont suspendu de 1912 à 175 mètres au-dessus du Rhumel : le plus haut du monde à son inauguration.', 'جسر معلق يعود لعام 1912 على ارتفاع 175 مترًا فوق وادي الرمال، كان الأعلى في العالم عند افتتاحه.',
    st_setsrid(st_makepoint(6.613, 36.371), 4326)::geography,
    null, 45, 120,
    'dz-cst-sidi-mcid',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/1_Pont_de_Sidi_M%27Cid.JPG/1280px-1_Pont_de_Sidi_M%27Cid.JPG', 'Yelles', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:1_Pont_de_Sidi_M%27Cid.JPG'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Palace of Ahmed Bey', 'Palais Ahmed Bey', 'قصر أحمد باي',
    'The last bey''s residence, finished in 1835: painted galleries, marble courts and orange gardens.', 'La résidence du dernier bey, achevée en 1835 : galeries peintes, cours de marbre et jardins d''orangers.', 'مقر آخر بايات قسنطينة، اكتمل عام 1835: أروقة مزخرفة وأفنية رخامية وحدائق برتقال.',
    st_setsrid(st_makepoint(6.611195, 36.367654), 4326)::geography,
    'Sat–Thu 09:00–16:30', 90, 90,
    'dz-cst-ahmed-bey',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Ahmed_Bey_Palace_10.jpg/1280px-Ahmed_Bey_Palace_10.jpg', 'Bernard Gagnon', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Ahmed_Bey_Palace_10.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Emir Abdelkader Mosque', 'Mosquée Emir Abdelkader', 'مسجد الأمير عبد القادر',
    'One of North Africa''s largest mosques, opened in 1994, its twin minarets rising 107 metres over the plateau.', 'L''une des plus grandes mosquées d''Afrique du Nord, ouverte en 1994, ses deux minarets culminant à 107 mètres.', 'أحد أكبر مساجد شمال إفريقيا، افتُتح عام 1994، وترتفع مئذنتاه التوأمان إلى 107 أمتار.',
    st_setsrid(st_makepoint(6.60305556, 36.34666667), 4326)::geography,
    null, 60, 150,
    'dz-cst-emir-abdelkader',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Abd_al-Q%C3%A1dir_18.jpg/1280px-Abd_al-Q%C3%A1dir_18.jpg', 'LBM1948', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Abd_al-Q%C3%A1dir_18.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000002'::uuid,
    'Cirta National Museum', 'Musée National Cirta', 'متحف سيرتا الوطني',
    'Numidian and Roman antiquities from the Constantine plateau, in a 1931 building above the Brèche.', 'Antiquités numides et romaines du plateau constantinois, dans un bâtiment de 1931 au-dessus de la Brèche.', 'آثار نوميدية ورومانية من هضبة قسنطينة، داخل مبنى يعود لعام 1931 فوق ساحة البريش.',
    st_setsrid(st_makepoint(6.60712309, 36.3628713), 4326)::geography,
    'Sat–Thu 09:00–16:30', 75, 70,
    'dz-cst-cirta',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Mus%C3%A9e_national_Cirta_03.jpg/1280px-Mus%C3%A9e_national_Cirta_03.jpg', 'Bernard Gagnon', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_national_Cirta_03.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000005'::uuid,
    'Rhumel Gorges', 'Gorges du Rhumel', 'أخاديد وادي الرمال',
    'The limestone chasm that severs the city, two hundred metres deep and crossed by six bridges.', 'La faille calcaire qui tranche la ville, deux cents mètres de profondeur et six ponts pour la franchir.', 'الأخدود الكلسي الذي يشق المدينة، بعمق مائتي متر وتعبره ستة جسور.',
    st_setsrid(st_makepoint(6.6155, 36.3665), 4326)::geography,
    null, 60, 200,
    'dz-cst-rhumel',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Le_rhumel_et_le_pont_romain.jpg/1280px-Le_rhumel_et_le_pont_romain.jpg', 'Mouhieddine kherouatou', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Le_rhumel_et_le_pont_romain.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Mellah Slimane Footbridge', 'Passerelle Mellah Slimane', 'جسر ملاح سليمان',
    'A 125-metre pedestrian suspension bridge of 1917, the shortcut between the old town and the station.', 'Passerelle suspendue piétonne de 125 mètres, ouverte en 1917, raccourci entre la vieille ville et la gare.', 'جسر مشاة معلق بطول 125 مترًا افتُتح عام 1917، وهو الطريق المختصر بين المدينة القديمة والمحطة.',
    st_setsrid(st_makepoint(6.617, 36.365), 4326)::geography,
    null, 30, 80,
    'dz-cst-mellah-slimane',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Passerelle_Mellah-Slimane_01.jpg/1280px-Passerelle_Mellah-Slimane_01.jpg', 'Bernard Gagnon', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Passerelle_Mellah-Slimane_01.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Sidi Rached Viaduct', 'Viaduc de Sidi Rached', 'جسر سيدي راشد',
    'A masonry viaduct of 1912 on twenty-seven arches, the largest stone bridge of its kind ever built.', 'Viaduc en maçonnerie de 1912 à vingt-sept arches, le plus grand pont de pierre de ce type jamais construit.', 'جسر حجري يعود لعام 1912 قائم على سبعة وعشرين قوسًا، أكبر جسر حجري من نوعه على الإطلاق.',
    st_setsrid(st_makepoint(6.612, 36.363), 4326)::geography,
    null, 40, 120,
    'dz-cst-sidi-rached',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Algerie_Constantine_Pont_Sidi_Rached.jpg/1280px-Algerie_Constantine_Pont_Sidi_Rached.jpg', 'Paebi', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Algerie_Constantine_Pont_Sidi_Rached.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000005'::uuid,
    'Monument aux Morts', 'Monument aux Morts', 'نصب الموتى',
    'A replica Arch of Trajan on the cliff edge, with the whole gorge and the bridges below it.', 'Réplique de l''arc de Trajan au bord de la falaise, avec toute la gorge et ses ponts en contrebas.', 'نسخة من قوس تراجان على حافة الجرف، تطل على الأخدود كاملًا وجسوره.',
    st_setsrid(st_makepoint(6.6136, 36.3752), 4326)::geography,
    null, 40, 100,
    'dz-cst-monument-aux-morts',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Monument_aux_morts_-_Constantine_%D9%85%D8%B9%D9%84%D9%85_%D8%AA%D8%B0%D9%83%D8%A7%D8%B1%D9%8A_-_%D9%82%D8%B3%D9%86%D8%B7%D9%8A%D9%86%D8%A9.jpg/1280px-Monument_aux_morts_-_Constantine_%D9%85%D8%B9%D9%84%D9%85_%D8%AA%D8%B0%D9%83%D8%A7%D8%B1%D9%8A_-_%D9%82%D8%B3%D9%86%D8%B7%D9%8A%D9%86%D8%A9.jpg', 'Habib kaki', 'CC0', 'https://commons.wikimedia.org/wiki/File:Monument_aux_morts_-_Constantine_%D9%85%D8%B9%D9%84%D9%85_%D8%AA%D8%B0%D9%83%D8%A7%D8%B1%D9%8A_-_%D9%82%D8%B3%D9%86%D8%B7%D9%8A%D9%86%D8%A9.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Salah Bey Viaduct', 'Viaduc Salah Bey', 'جسر صالح باي',
    'A cable-stayed bridge of 2014, 756 metres long, the modern counterpart to the city''s stone crossings.', 'Pont à haubans de 2014, long de 756 mètres, pendant contemporain des franchissements de pierre de la ville.', 'جسر بأسلاك مشدودة افتُتح عام 2014 بطول 756 مترًا، النظير الحديث لجسور المدينة الحجرية.',
    st_setsrid(st_makepoint(6.614478, 36.357405), 4326)::geography,
    null, 30, 150,
    'dz-cst-salah-bey',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pont_Salah_Bey_%2849475835572%29.jpg/1280px-Pont_Salah_Bey_%2849475835572%29.jpg', 'hanming_huang from Singapore', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Pont_Salah_Bey_(49475835572).jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Souk El Ghezel Mosque', 'Mosquée Souk El Ghezel', 'جامع سوق الغزل',
    'An Ottoman mosque of 1730 on the old wool market, briefly a cathedral, restored to prayer in 1962.', 'Mosquée ottomane de 1730 sur l''ancien marché à la laine, brièvement cathédrale, rendue au culte en 1962.', 'جامع عثماني يعود لعام 1730 في سوق الصوف القديم، صار كاتدرائية لفترة ثم أُعيد للصلاة عام 1962.',
    st_setsrid(st_makepoint(6.614, 36.364), 4326)::geography,
    null, 35, 60,
    'dz-cst-souk-el-ghezel',
    'https://upload.wikimedia.org/wikipedia/commons/2/20/Constantine_%28Alg%C3%A9rie%29_Cath%C3%A9drale.jpg', 'Unknown author Unknown author', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Constantine_(Alg%C3%A9rie)_Cath%C3%A9drale.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000004'::uuid,
    'Sidi El Kettani Mosque', 'Mosquée Sidi El Kettani', 'جامع سيدي الكتاني',
    'Built by Salah Bey in 1776 with a madrasa and hammam around it, in the heart of the old town.', 'Élevée par Salah Bey en 1776 avec sa médersa et son hammam, au cœur de la vieille ville.', 'شيّده صالح باي عام 1776 ومعه مدرسة وحمّام، في قلب المدينة القديمة.',
    st_setsrid(st_makepoint(6.61, 36.3665), 4326)::geography,
    null, 35, 60,
    'dz-cst-sidi-el-kettani',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fonds_Andr%C3%A9_Raymond_%281925-2011%29_-_Alg%C3%A9rie_-_Constantine_-_Mosqu%C3%A9e_et_medersa_El-Kettani_%28M%C3%A9diHAL_4427108%29.jpg/1280px-Fonds_Andr%C3%A9_Raymond_%281925-2011%29_-_Alg%C3%A9rie_-_Constantine_-_Mosqu%C3%A9e_et_medersa_El-Kettani_%28M%C3%A9diHAL_4427108%29.jpg', 'Maison Méditerranéenne Des Sciences de l''Homme Phonothèque, André Raymond', 'Licence Ouverte', 'https://commons.wikimedia.org/wiki/File:Fonds_Andr%C3%A9_Raymond_(1925-2011)_-_Alg%C3%A9rie_-_Constantine_-_Mosqu%C3%A9e_et_medersa_El-Kettani_(M%C3%A9diHAL_4427108).jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Tiddis', 'Tiddis', 'تيديس',
    'A Roman hill town of red rock thirty kilometres north-west, its stepped main street cut into the slope.', 'Cité romaine de roche rouge à trente kilomètres au nord-ouest, sa rue principale taillée en escalier dans la pente.', 'مدينة رومانية من الصخر الأحمر على بعد ثلاثين كيلومترًا شمال غرب، شارعها الرئيسي محفور مدرجًا في المنحدر.',
    st_setsrid(st_makepoint(6.48388889, 36.46333333), 4326)::geography,
    null, 90, 250,
    'dz-cst-tiddis',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Tiddis_01.jpg/1280px-Tiddis_01.jpg', 'Bernard Gagnon', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Tiddis_01.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Mausoleum of Massinissa', 'Mausolée de Massinissa', 'ضريح ماسينيسا',
    'The stepped Numidian tower at El Khroub, held to be the tomb of the first king of a united Numidia.', 'Tour numide à degrés du Khroub, tenue pour le tombeau du premier roi de la Numidie unifiée.', 'البرج النوميدي المدرج بالخروب، ويُعتقد أنه قبر أول ملوك نوميديا الموحدة.',
    st_setsrid(st_makepoint(6.6928, 36.2617), 4326)::geography,
    null, 45, 120,
    'dz-cst-massinissa',
    'https://upload.wikimedia.org/wikipedia/commons/b/bc/Massinissa_grave.jpg', 'No machine-readable author provided. Horatius assumed (based on copyright claims).', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Massinissa_grave.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000006'::uuid,
    'Constantine Regional Theatre', 'Théâtre Régional de Constantine', 'المسرح الجهوي لقسنطينة',
    'An Italianate theatre of 1883 on the Place de la Brèche, restored for the 2015 Capital of Arab Culture.', 'Théâtre à l''italienne de 1883 sur la place de la Brèche, restauré pour la capitale de la culture arabe 2015.', 'مسرح على الطراز الإيطالي شُيد عام 1883 بساحة البريش، رُمم بمناسبة عاصمة الثقافة العربية 2015.',
    st_setsrid(st_makepoint(6.6117, 36.3648), 4326)::geography,
    null, 40, 60,
    'dz-cst-theatre',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Int%C3%A9rieur_du_th%C3%A9%C3%A2tre_de_Constantine.jpg/1280px-Int%C3%A9rieur_du_th%C3%A9%C3%A2tre_de_Constantine.jpg', 'Mouhieddinek', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Int%C3%A9rieur_du_th%C3%A9%C3%A2tre_de_Constantine.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000003'::uuid,
    'Djebel El Ouahch', 'Djebel El Ouahch', 'جبل الوحش',
    'A pine forest park in the hills north-east of the city, with lakes and the local weekend picnic ground.', 'Parc forestier de pins dans les collines au nord-est, avec ses lacs et les pique-niques du week-end.', 'حديقة غابية من الصنوبر في التلال شمال شرق المدينة، ببحيراتها ومتنزهات نهاية الأسبوع.',
    st_setsrid(st_makepoint(6.6644, 36.4005), 4326)::geography,
    null, 90, 400,
    'dz-cst-djebel-ouahch',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Djbel_El_Ouahch_Constantine_1.jpg/1280px-Djbel_El_Ouahch_Constantine_1.jpg', 'MHadi 2015', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Djbel_El_Ouahch_Constantine_1.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Constantine Casbah', 'Casbah de Constantine', 'قصبة قسنطينة',
    'The old quarter on the rock''s northern tip, where Ottoman houses stop at the edge of the gorge.', 'Le vieux quartier à la pointe nord du rocher, où les maisons ottomanes s''arrêtent au bord du gouffre.', 'الحي القديم في الطرف الشمالي للصخرة، حيث تنتهي البيوت العثمانية عند حافة الهاوية.',
    st_setsrid(st_makepoint(6.611, 36.369), 4326)::geography,
    null, 60, 200,
    'dz-cst-casbah',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Constantine_medina.jpg/1280px-Constantine_medina.jpg', 'Mouhieddine Kherouatou', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Constantine_medina.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'Roman Aqueduct of Constantine', 'Aqueduc romain de Constantine', 'القناة الرومانية بقسنطينة',
    'The surviving arches of the aqueduct that carried water to Roman Cirta across the Rhumel valley.', 'Les arches subsistantes de l''aqueduc qui portait l''eau à la Cirta romaine par-dessus la vallée du Rhumel.', 'الأقواس المتبقية من القناة التي كانت تنقل المياه إلى سيرتا الرومانية عبر وادي الرمال.',
    st_setsrid(st_makepoint(6.6176, 36.3502), 4326)::geography,
    null, 35, 100,
    'dz-cst-aqueduc',
    'https://upload.wikimedia.org/wikipedia/commons/6/62/Environs_de_Constantine._Ruines_d%27un_Aqueduct_Romain_-_ND._Phot._LCCN2004665041.jpg', 'Neurdein frer̀es, photographer', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Environs_de_Constantine._Ruines_d%27un_Aqueduct_Romain_-_ND._Phot._LCCN2004665041.jpg'
  ),
  (
    '00000000-0000-4000-a000-000000000030'::uuid, '00000000-0000-4000-b000-000000000001'::uuid,
    'El Kantara Bridge', 'Pont El Kantara', 'جسر القنطرة',
    'The oldest crossing of the gorge, Roman in foundation and rebuilt in iron in 1863.', 'Le plus ancien franchissement de la gorge, d''assise romaine et reconstruit en fer en 1863.', 'أقدم معابر الأخدود، أساسه روماني وأُعيد بناؤه بالحديد عام 1863.',
    st_setsrid(st_makepoint(6.618, 36.368), 4326)::geography,
    null, 30, 90,
    'dz-cst-el-kantara',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Constantine_bridge_1899.jpg/1280px-Constantine_bridge_1899.jpg', 'Unknown author Unknown author', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Constantine_bridge_1899.jpg'
  );

update public.pois set source = 'team_seeded', status = 'published', verified_by = 'poi_seed_tool';

commit;
