"""Rewrite `location_translations.blurb` for rows ingested before
`ingestion/describe.py` existed.

Same reasoning as backfill_photos.py: fixing the pipeline only affects POIs as
they are ingested, and `poi_tiles` keeps an already-fetched tile out of the
pipeline until it expires — so without this, the catalogue keeps its "A
attraction attraction." blurbs for the rest of the tile TTL.

Only rewrites blurbs that look machine-generated by the old code. A blurb
derived from Wikipedia (longer, real prose) is left alone. Dry-run by default.

    python backfill_descriptions.py                 # report what would change
    python backfill_descriptions.py --apply
    python backfill_descriptions.py --apply --llm   # allow the LLM pass
"""
from __future__ import annotations

import argparse
import logging
import sys
import time

from ingestion import describe
from ingestion.supabase_admin import get_admin_client

logger = logging.getLogger(__name__)

# The shapes the previous format-string branch could produce. Anything longer
# than this is either Wikipedia-derived or already rewritten, and is skipped.
_STALE_MAX_CHARS = 60


def _looks_generated(blurb: str | None) -> bool:
    if not blurb:
        return True
    text = blurb.strip()
    if len(text) > _STALE_MAX_CHARS:
        return False
    lowered = text.lower()
    return (
        lowered.startswith(("a ", "an ", "the "))
        # the tells of the old builder
        or " in the area." in lowered
        or lowered.endswith(" attraction.")
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="write results (default is dry-run)")
    parser.add_argument("--llm", action="store_true",
                        help="allow the LLM pass for POIs with enough facts")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--place", default=None, help="fallback city name, e.g. 'Algiers'")
    args = parser.parse_args()

    logging.basicConfig(level=logging.WARNING, format="%(levelname)s %(message)s")
    client = get_admin_client()

    query = client.table("locations").select(
        "id,category,osm_tags,heritage_status,wikipedia_title,"
        "location_translations(locale,name,blurb)"
    )
    if args.limit:
        query = query.limit(args.limit)
    rows = query.execute().data or []

    changed = 0
    skipped = 0
    for i, row in enumerate(rows, 1):
        translations = row.get("location_translations") or []
        en = next((t for t in translations if t.get("locale") == "en"), None)
        if not en:
            continue

        old = en.get("blurb")
        if not _looks_generated(old):
            skipped += 1
            continue

        tags = row.get("osm_tags") or {}
        facts = describe.collect_facts(
            name=en.get("name") or row["id"],
            category=row.get("category"),
            tags=tags,
            heritage_status=row.get("heritage_status"),
            place=args.place or tags.get("addr:city"),
        )
        new = describe.describe(facts, use_llm=args.llm)

        if not new or new == old:
            continue

        changed += 1
        print(f"{i:4}/{len(rows)}  {(en.get('name') or '')[:32]:32}")
        print(f"        - {old}")
        print(f"        + {new}")

        if args.apply:
            client.table("location_translations").update({"blurb": new}).eq(
                "location_id", row["id"]).eq("locale", "en").execute()
        sys.stdout.flush()
        if args.llm:
            time.sleep(0.3)  # the LLM path is rate-limited; the rest is local

    print(f"\n{changed} to rewrite, {skipped} left alone (not machine-generated)")
    if changed and not args.apply:
        print("dry run — nothing written. Re-run with --apply to persist.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
