/**
 * Rewrite `location_translations.blurb` for rows ingested before
 * `ingestion/describe.ts` existed.
 *
 * Same reasoning as backfillPhotos.ts: fixing the pipeline only affects POIs as
 * they are ingested, and `poi_tiles` keeps an already-fetched tile out of the
 * pipeline until it expires — so without this, the catalogue keeps its "A
 * attraction attraction." blurbs for the rest of the tile TTL.
 *
 * Only rewrites blurbs that look machine-generated by the old code. A blurb
 * derived from Wikipedia (longer, real prose) is left alone. Dry-run by default.
 *
 *     npm run backfill:descriptions                    # report what would change
 *     npm run backfill:descriptions -- --apply
 *     npm run backfill:descriptions -- --apply --llm   # allow the LLM pass
 */
import { parseArgs } from "util";

import { sleep } from "../async";
import * as describe from "../ingestion/describe";
import { getAdminClient } from "../ingestion/supabaseAdmin";
import { unwrapRows } from "../supabase";
import { HeritageStatus, OsmTags } from "../types";

// The shapes the previous format-string branch could produce. Anything longer
// than this is either Wikipedia-derived or already rewritten, and is skipped.
const STALE_MAX_CHARS = 60;

function looksGenerated(blurb: string | null | undefined): boolean {
  if (!blurb) return true;
  const text = blurb.trim();
  if (text.length > STALE_MAX_CHARS) return false;
  const lowered = text.toLowerCase();
  return (
    lowered.startsWith("a ") ||
    lowered.startsWith("an ") ||
    lowered.startsWith("the ") ||
    // the tells of the old builder
    lowered.includes(" in the area.") ||
    lowered.endsWith(" attraction.")
  );
}

interface Row {
  id: string;
  category: string | null;
  osm_tags: OsmTags | null;
  heritage_status: HeritageStatus;
  wikipedia_title: string | null;
  location_translations?: Array<{ locale: string; name: string; blurb: string }> | null;
}

function pad(text: string, width: number): string {
  return text.length >= width ? text.slice(0, width) : text + " ".repeat(width - text.length);
}

async function main(): Promise<number> {
  const { values } = parseArgs({
    options: {
      apply: { type: "boolean", default: false },
      llm: { type: "boolean", default: false },
      limit: { type: "string" },
      place: { type: "string" },
    },
    allowPositionals: false,
  });
  const apply = values.apply === true;
  const useLlm = values.llm === true;
  const limit = values.limit ? Number.parseInt(values.limit, 10) : null;
  const place = values.place ?? null;

  const client = getAdminClient();

  let query = client
    .from("locations")
    .select(
      "id,category,osm_tags,heritage_status,wikipedia_title," +
        "location_translations(locale,name,blurb)",
    );
  if (limit) {
    query = query.limit(limit);
  }
  const rows = await unwrapRows<Row>(query);

  let changed = 0;
  let skipped = 0;
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const translations = row.location_translations ?? [];
    const en = translations.find((t) => t.locale === "en");
    if (!en) continue;

    const old = en.blurb;
    if (!looksGenerated(old)) {
      skipped += 1;
      continue;
    }

    const tags = row.osm_tags ?? {};
    const facts = describe.collectFacts({
      name: en.name || row.id,
      category: row.category,
      tags,
      heritageStatus: row.heritage_status,
      place: place ?? tags["addr:city"] ?? null,
    });
    const next = await describe.describe(facts, { useLlm });

    if (!next || next === old) continue;

    changed += 1;
    console.log(`${String(i + 1).padStart(4)}/${rows.length}  ${pad(en.name ?? "", 32)}`);
    console.log(`        - ${old}`);
    console.log(`        + ${next}`);

    if (apply) {
      await client
        .from("location_translations")
        .update({ blurb: next })
        .eq("location_id", row.id)
        .eq("locale", "en");
    }
    if (useLlm) {
      await sleep(300); // the LLM path is rate-limited; the rest is local
    }
  }

  console.log(`\n${changed} to rewrite, ${skipped} left alone (not machine-generated)`);
  if (changed && !apply) {
    console.log("dry run — nothing written. Re-run with --apply to persist.");
  }
  return 0;
}

main().then(
  (code) => process.exit(code),
  (error) => {
    console.error(error);
    process.exit(1);
  },
);
