-- Task scores, saved per user.
--
-- `profiles.total_points` already existed but nothing ever wrote to it: points
-- lived only in AppState and SharedPreferences, so they died with the tour and
-- did not follow the traveller to another device.
--
-- The counter alone would not have been enough. The client retries writes it
-- made while offline, and restores a persisted session on launch, so "add 30
-- points" is an operation that gets replayed — and replaying an increment
-- double-counts. This is therefore a ledger of individual completions with a
-- client-supplied idempotency key, and the counter on `profiles` is derived
-- from it by trigger so the common read ("what is my score") stays a single
-- column lookup.

create table if not exists public.task_completions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,

  -- Idempotency key, generated by the client from what it is recording (the
  -- route and the stop index). Replaying the same completion hits the unique
  -- constraint and is discarded rather than awarded twice.
  completion_key text not null,

  -- Deliberately text with no foreign key, both of them. The catalogue tables
  -- are empty in this pilot and the app runs on demo routes whose ids exist
  -- nowhere in the database — a foreign key here would reject the writes this
  -- table exists to keep. It is a record of what the traveller did, and it
  -- must not depend on the catalogue agreeing that the place was real.
  route_id text,
  poi_id text,

  task_type text not null default 'unknown',

  -- Bounded so a malformed or hostile client cannot mint an arbitrary score
  -- in one row. Tasks are worth 30; the ceiling is loose enough to leave room
  -- for bonuses without being unlimited.
  points integer not null default 0 check (points >= 0 and points <= 500),

  completed_at timestamptz not null default now(),

  constraint task_completions_key_unique unique (user_id, completion_key)
);

-- The unique constraint already indexes (user_id, completion_key), which is
-- what the RLS predicate and the idempotency check both need. This one is for
-- reading a traveller's history newest-first.
create index if not exists task_completions_user_completed_idx
  on public.task_completions (user_id, completed_at desc);

-- ---------------------------------------------------------------------------
-- Keeping profiles.total_points in step
-- ---------------------------------------------------------------------------
-- SECURITY INVOKER on purpose. The "own profile" policy already permits a user
-- to update their own row, and `new.user_id` is pinned to `auth.uid()` by this
-- table's own insert policy, so the update this performs is one the caller was
-- always allowed to make. SECURITY DEFINER would buy nothing here and would
-- turn a trigger into a privilege escalation if the insert policy ever
-- loosened.
create or replace function public.apply_task_completion_points()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.profiles
     set total_points = total_points + new.points,
         updated_at = now()
   where id = new.user_id;
  return new;
end;
$$;

drop trigger if exists task_completions_award_points on public.task_completions;
create trigger task_completions_award_points
  after insert on public.task_completions
  for each row execute function public.apply_task_completion_points();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.task_completions enable row level security;

-- Split by command rather than one FOR ALL policy, because this table is
-- append-only by design: there is no UPDATE or DELETE policy, so a completion
-- cannot be edited or removed to launder a score, and `total_points` cannot
-- drift away from the ledger that explains it.
drop policy if exists "own task completions read" on public.task_completions;
create policy "own task completions read" on public.task_completions
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "own task completions insert" on public.task_completions;
create policy "own task completions insert" on public.task_completions
  for insert to authenticated
  with check ((select auth.uid()) = user_id);

-- Anonymous sign-ins carry the `authenticated` role, so this covers the
-- traveller who has not signed up yet. Their uid survives `updateUser`, which
-- is how points earned before signup follow them into the account.
grant select, insert on public.task_completions to authenticated;
